// Generated by @forge-clients/generator — DO NOT EDIT
// Source: Confluence Cloud REST API v2
/* eslint-disable */
// prettier-ignore
export interface AdminKeyResponse {
    /** User identifier. */
    accountId?: string;
    /** Timestamp in UTC that represents when the admin key will expire. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    expirationTime?: string;
}

export interface AttachmentSingle {
    /** ID of the attachment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** Date and time when the attachment was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /**
     * ID of the containing page.
     *
     * Note: This is only returned if the attachment has a container that is a page.
     */
    pageId?: string;
    /**
     * ID of the containing blog post.
     *
     * Note: This is only returned if the attachment has a container that is a blog post.
     */
    blogPostId?: string;
    /**
     * ID of the containing custom content.
     *
     * Note: This is only returned if the attachment has a container that is custom content.
     */
    customContentId?: string;
    /** Media Type for the attachment. */
    mediaType?: string;
    /** Media Type description for the attachment. */
    mediaTypeDescription?: string;
    /** Comment for the attachment. */
    comment?: string;
    /** File ID of the attachment. This is the ID referenced in `atlas_doc_format` bodies and is distinct from the attachment ID. */
    fileId?: string;
    /** File size of the attachment. */
    fileSize?: number;
    /** WebUI link of the attachment. */
    webuiLink?: string;
    /** Download link of the attachment. */
    downloadLink?: string;
    version?: Version;
    labels?: { results?: Array<Label>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    properties?: { results?: Array<ContentProperty>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    operations?: { results?: Array<Operation>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    versions?: { results?: Array<Version>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    _links?: AttachmentLinks;
}

export interface AttachmentBulk {
    /** ID of the attachment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** Date and time when the attachment was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /**
     * ID of the containing page.
     *
     * Note: This is only returned if the attachment has a container that is a page.
     */
    pageId?: string;
    /**
     * ID of the containing blog post.
     *
     * Note: This is only returned if the attachment has a container that is a blog post.
     */
    blogPostId?: string;
    /**
     * ID of the containing custom content.
     *
     * Note: This is only returned if the attachment has a container that is custom content.
     */
    customContentId?: string;
    /** Media Type for the attachment. */
    mediaType?: string;
    /** Media Type description for the attachment. */
    mediaTypeDescription?: string;
    /** Comment for the attachment. */
    comment?: string;
    /** File ID of the attachment. This is the ID referenced in `atlas_doc_format` bodies and is distinct from the attachment ID. */
    fileId?: string;
    /** File size of the attachment. */
    fileSize?: number;
    /** WebUI link of the attachment. */
    webuiLink?: string;
    /** Download link of the attachment. */
    downloadLink?: string;
    version?: Version;
    _links?: AttachmentLinks;
}

export interface BlogPostSingle {
    /** ID of the blog post. */
    id?: string;
    status?: BlogPostContentStatus;
    /** Title of the blog post. */
    title?: string;
    /** ID of the space the blog post is in. */
    spaceId?: string;
    /** The account ID of the user who created this blog post originally. */
    authorId?: string;
    /** Date and time when the blog post was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    version?: Version;
    body?: BodySingle;
    labels?: { results?: Array<Label>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    properties?: { results?: Array<ContentProperty>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    operations?: { results?: Array<Operation>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    likes?: { results?: Array<Like>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    versions?: { results?: Array<Version>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    /** Whether the blog post has been favorited by the current user. */
    isFavoritedByCurrentUser?: boolean;
    _links?: AbstractPageLinks;
}

export interface BlogPostBulk {
    /** ID of the blog post. */
    id?: string;
    status?: BlogPostContentStatus;
    /** Title of the blog post. */
    title?: string;
    /** ID of the space the blog post is in. */
    spaceId?: string;
    /** The account ID of the user who created this blog post originally. */
    authorId?: string;
    /** Date and time when the blog post was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    version?: Version;
    body?: BodyBulk;
    _links?: AbstractPageLinks;
}

/** Contains fields for each representation type requested. */
export interface TaskBodySingle {
    storage?: BodyType;
    atlas_doc_format?: BodyType;
}

/** Contains fields for each representation type requested. */
export interface BodySingle {
    storage?: BodyType;
    atlas_doc_format?: BodyType;
    view?: BodyType;
}

/** Contains fields for each representation type requested. */
export interface BodyBulk {
    storage?: BodyType;
    atlas_doc_format?: BodyType;
}

export interface BodyType {
    /** Type of content representation used for the value field. */
    representation?: string;
    /** Body of the content, in the format found in the representation field. */
    value?: string;
}

/** The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases. */
export type PrimaryBodyRepresentation = "storage" | "atlas_doc_format";
/** The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases. */
export type PrimaryBodyRepresentationSingle = "storage" | "atlas_doc_format" | "view" | "export_view" | "anonymous_export_view" | "styled_view" | "editor";
/** The formats a custom content body can be represented as. A subset of BodyRepresentation. */
export type CustomContentBodyRepresentation = "raw" | "storage" | "atlas_doc_format";
/** The formats a custom content body can be represented as. A subset of BodyRepresentation. */
export type CustomContentBodyRepresentationSingle = "raw" | "storage" | "atlas_doc_format" | "view" | "export_view" | "anonymous_export_view";
/** The formats a space description can be represented as. A subset of BodyRepresentation. */
export type SpaceDescriptionBodyRepresentation = "plain" | "view";

export interface ContentIdToContentTypeResponse {
    /**
     * JSON object containing all requested content ids as keys and their associated content types as the values.
     * Duplicate content ids in the request will be returned under a single key in the response. For built-in content
     * types, the enumerations are as specified. Custom content ids will be mapped to their associated type.
     */
    results?: Record<string, "page" | "blogpost" | "attachment" | "footer-comment" | "inline-comment" | string>;
}

/** The status of the content. */
export type ContentStatus = "current" | "draft" | "archived" | "historical" | "trashed" | "deleted" | "any";
/** The status of the content. */
export type BlogPostContentStatus = "current" | "draft" | "historical" | "trashed" | "deleted" | "any";
/** The status of the content. */
export type OnlyArchivedAndCurrentContentStatus = "current" | "archived";

export interface ContentProperty {
    /** ID of the property */
    id?: string;
    /** Key of the property */
    key?: string;
    /** Value of the property. Must be a valid JSON value. */
    value?: Record<string, unknown>;
    version?: Version;
}

export interface ContentPropertyCreateRequest {
    /** Key of the content property */
    key?: string;
    /** Value of the content property. */
    value?: Record<string, unknown>;
}

export interface ContentPropertyUpdateRequest {
    /** Key of the content property */
    key?: string;
    /** Value of the content property. */
    value?: Record<string, unknown>;
    /** New version number and associated message */
    version?: { number?: number; message?: string };
}

export interface CustomContentSingle {
    /** ID of the custom content. */
    id?: string;
    /** The type of custom content. */
    type?: string;
    status?: ContentStatus;
    /** Title of the custom content. */
    title?: string;
    /**
     * ID of the space the custom content is in.
     *
     * Note: This is always returned, regardless of if the custom content has a container that is a space.
     */
    spaceId?: string;
    /**
     * ID of the containing page.
     *
     * Note: This is only returned if the custom content has a container that is a page.
     */
    pageId?: string;
    /**
     * ID of the containing blog post.
     *
     * Note: This is only returned if the custom content has a container that is a blog post.
     */
    blogPostId?: string;
    /**
     * ID of the containing custom content.
     *
     * Note: This is only returned if the custom content has a container that is custom content.
     */
    customContentId?: string;
    /** The account ID of the user who created this custom content originally. */
    authorId?: string;
    /** Date and time when the custom content was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    version?: Version;
    labels?: { results?: Array<Label>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    properties?: { results?: Array<ContentProperty>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    operations?: { results?: Array<Operation>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    versions?: { results?: Array<Version>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    body?: CustomContentBodySingle;
    _links?: CustomContentLinks;
}

export interface CustomContentBulk {
    /** ID of the custom content. */
    id?: string;
    /** The type of custom content. */
    type?: string;
    status?: ContentStatus;
    /** Title of the custom content. */
    title?: string;
    /**
     * ID of the space the custom content is in.
     *
     * Note: This is always returned, regardless of if the custom content has a container that is a space.
     */
    spaceId?: string;
    /**
     * ID of the containing page.
     *
     * Note: This is only returned if the custom content has a container that is a page.
     */
    pageId?: string;
    /**
     * ID of the containing blog post.
     *
     * Note: This is only returned if the custom content has a container that is a blog post.
     */
    blogPostId?: string;
    /**
     * ID of the containing custom content.
     *
     * Note: This is only returned if the custom content has a container that is custom content.
     */
    customContentId?: string;
    /** The account ID of the user who created this custom content originally. */
    authorId?: string;
    /** Date and time when the custom content was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    version?: Version;
    body?: CustomContentBodyBulk;
    _links?: CustomContentLinks;
}

/** Contains fields for each representation type requested. */
export interface CustomContentBodySingle {
    raw?: BodyType;
    storage?: BodyType;
    atlas_doc_format?: BodyType;
    view?: BodyType;
}

/** Contains fields for each representation type requested. */
export interface CustomContentBodyBulk {
    raw?: BodyType;
    storage?: BodyType;
    atlas_doc_format?: BodyType;
}

export interface DetailedVersion {
    /** The current version number. */
    number?: number;
    /** The account ID of the user who created this version. */
    authorId?: string;
    /** Message associated with the current version. */
    message?: string;
    /** Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions. */
    minorEdit?: boolean;
    /** Describes if the content type is modified in this version (e.g. page to blog) */
    contentTypeModified?: boolean;
    /** The account IDs of users that collaborated on this version. */
    collaborators?: Array<string>;
    /** The version number of the version prior to this current content update. */
    prevVersion?: number;
    /** The version number of the version after this current content update. */
    nextVersion?: number;
}

export interface Label {
    /** ID of the label. */
    id?: string;
    /** Name of the label. */
    name?: string;
    /** Prefix of the label. */
    prefix?: string;
}

export interface Like {
    /** Account ID. */
    accountId?: string;
}

export interface Operation {
    /** The type of operation. */
    operation?: string;
    /** The type of entity the operation type targets. */
    targetType?: string;
}

/** The list of operations permitted on entity. */
export interface PermittedOperationsResponse {
    operations?: Array<Operation>;
}

export interface PageSingle {
    /** ID of the page. */
    id?: string;
    status?: ContentStatus;
    /** Title of the page. */
    title?: string;
    /** ID of the space the page is in. */
    spaceId?: string;
    /** ID of the parent page, or null if there is no parent page. */
    parentId?: string;
    parentType?: ParentContentType;
    /** Position of child page within the given parent page tree. */
    position?: number;
    /** The account ID of the user who created this page originally. */
    authorId?: string;
    /** The account ID of the user who owns this page. */
    ownerId?: string;
    /** The account ID of the user who owned this page previously, or null if there is no previous owner. */
    lastOwnerId?: string;
    /** Date and time when the page was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    version?: Version;
    body?: BodySingle;
    labels?: { results?: Array<Label>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    properties?: { results?: Array<ContentProperty>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    operations?: { results?: Array<Operation>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    likes?: { results?: Array<Like>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    versions?: { results?: Array<Version>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    /** Whether the page has been favorited by the current user. */
    isFavoritedByCurrentUser?: boolean;
    _links?: AbstractPageLinks;
}

export interface PageBulk {
    /** ID of the page. */
    id?: string;
    status?: ContentStatus;
    /** Title of the page. */
    title?: string;
    /** ID of the space the page is in. */
    spaceId?: string;
    /** ID of the parent page, or null if there is no parent page. */
    parentId?: string;
    parentType?: ParentContentType;
    /** Position of child page within the given parent page tree. */
    position?: number;
    /** The account ID of the user who created this page originally. */
    authorId?: string;
    /** The account ID of the user who owns this page. */
    ownerId?: string;
    /** The account ID of the user who owned this page previously, or null if there is no previous owner. */
    lastOwnerId?: string;
    /** The subtype of the page. */
    subtype?: string;
    /** Date and time when the page was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    version?: Version;
    body?: BodyBulk;
    _links?: AbstractPageLinks;
}

/** Content type of the parent, or null if there is no parent. */
export type ParentContentType = "page" | "whiteboard" | "database" | "embed" | "folder";

export interface PageBodyWrite {
    /** Type of content representation used for the value field. */
    representation?: "storage" | "atlas_doc_format" | "wiki";
    /** Body of the page, in the format found in the representation field. */
    value?: string;
}

/**
 * Body of the page. Only one body format should be specified as the property
 * for this object, e.g. `storage`.
 */
export interface PageNestedBodyWrite {
    storage?: PageBodyWrite;
    atlas_doc_format?: PageBodyWrite;
    wiki?: PageBodyWrite;
}

export interface BlogPostBodyWrite {
    /** Type of content representation used for the value field. */
    representation?: "storage" | "atlas_doc_format" | "wiki";
    /** Body of the blog post, in the format found in the representation field. */
    value?: string;
}

/**
 * Body of the blog post. Only one body format should be specified as the property
 * for this object, e.g. `storage`.
 */
export interface BlogPostNestedBodyWrite {
    storage?: BlogPostBodyWrite;
    atlas_doc_format?: BlogPostBodyWrite;
    wiki?: BlogPostBodyWrite;
}

export interface CommentBodyWrite {
    /** Type of content representation used for the value field. */
    representation?: "storage" | "atlas_doc_format" | "wiki";
    /** Body of the comment, in the format found in the representation field. */
    value?: string;
}

/**
 * Body of the comment. Only one body format should be specified as the property
 * for this object, e.g. `storage`.
 */
export interface CommentNestedBodyWrite {
    storage?: CommentBodyWrite;
    atlas_doc_format?: CommentBodyWrite;
    wiki?: CommentBodyWrite;
}

export interface CustomContentBodyWrite {
    /** Type of content representation used for the value field. */
    representation?: "storage" | "atlas_doc_format" | "raw";
    /** Body of the custom content, in the format found in the representation field. */
    value?: string;
}

/**
 * Body of the custom content. Only one body format should be specified as the property
 * for this object, e.g. `storage`.
 */
export interface CustomContentNestedBodyWrite {
    storage?: CustomContentBodyWrite;
    atlas_doc_format?: CustomContentBodyWrite;
    raw?: CustomContentBodyWrite;
}

export interface ChildPage {
    /** ID of the page. */
    id?: string;
    status?: OnlyArchivedAndCurrentContentStatus;
    /** Title of the page. */
    title?: string;
    /** ID of the space the page is in. */
    spaceId?: string;
    /** Position of child page within the given parent page tree. */
    childPosition?: number;
}

export interface ChildCustomContent {
    /** ID of the child custom content. */
    id?: string;
    status?: OnlyArchivedAndCurrentContentStatus;
    /** Title of the custom content. */
    title?: string;
    /** Custom content type. */
    type?: string;
    /** ID of the space the custom content is in. */
    spaceId?: string;
}

export interface ChildrenResponse {
    /** ID of the child content. */
    id?: string;
    status?: OnlyArchivedAndCurrentContentStatus;
    /** Title of the child content. */
    title?: string;
    /** Hierarchical content type (database/embed/folder/page/whiteboard). */
    type?: string;
    /** ID of the space the content is in. */
    spaceId?: string;
    /**
     * Numerical value indicating position of the content relative to its siblings (with the same parentId) within the content tree.
     * If the content is sorted by childPosition, it will reflect the default content ordering within the content tree.
     */
    childPosition?: number;
}

export interface DescendantsResponse {
    /** ID of the descendant. */
    id?: string;
    status?: OnlyArchivedAndCurrentContentStatus;
    /** Title of the descendant. */
    title?: string;
    /** Hierarchical content type (database/embed/folder/page/whiteboard). */
    type?: string;
    /** ID of the parent content. */
    parentId?: string;
    /** Depth of the descendant in the content tree relative to the content specified in the request. */
    depth?: number;
    /**
     * Numerical value indicating position of the content relative to its siblings (with the same parentId) within the content tree.
     * If the content is sorted by childPosition, it will reflect the default content ordering within the content tree.
     */
    childPosition?: number;
}

export interface WhiteboardSingle {
    /** ID of the whiteboard. */
    id?: string;
    /** The content type of the object. */
    type?: string;
    status?: ContentStatus;
    /** Title of the whiteboard. */
    title?: string;
    /** ID of the parent content, or null if there is no parent content. */
    parentId?: string;
    parentType?: ParentContentType;
    /** Position of the whiteboard within the given parent page tree. */
    position?: number;
    /** The account ID of the user who created this whiteboard originally. */
    authorId?: string;
    /** The account ID of the user who owns this whiteboard. */
    ownerId?: string;
    /** Date and time when the whiteboard was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** ID of the space the whiteboard is in. */
    spaceId?: string;
    version?: Version;
    _links?: WhiteboardLinks;
}

export interface DatabaseSingle {
    /** ID of the database. */
    id?: string;
    /** The content type of the object. */
    type?: string;
    status?: ContentStatus;
    /** Title of the database. */
    title?: string;
    /** ID of the parent content, or null if there is no parent content. */
    parentId?: string;
    parentType?: ParentContentType;
    /** Position of the database within the given parent page tree. */
    position?: number;
    /** The account ID of the user who created this database originally. */
    authorId?: string;
    /** The account ID of the user who owns this database. */
    ownerId?: string;
    /** Date and time when the database was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** ID of the space the database is in. */
    spaceId?: string;
    version?: Version;
    _links?: DatabaseLinks;
}

export interface SmartLinkSingle {
    /** ID of the Smart Link in the content tree. */
    id?: string;
    /** The content type of the object. */
    type?: string;
    status?: ContentStatus;
    /** Title of the Smart Link in the content tree. */
    title?: string;
    /** ID of the parent content, or null if there is no parent content. */
    parentId?: string;
    parentType?: ParentContentType;
    /** Position of the Smart Link within the given parent page tree. */
    position?: number;
    /** The account ID of the user who created this Smart Link in the content tree originally. */
    authorId?: string;
    /** The account ID of the user who owns this Smart Link in the content tree. */
    ownerId?: string;
    /** Date and time when the Smart Link in the content tree was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** The embedded URL of the Smart Link. If the Smart Link does not have an embedded URL, this property will not be included in the response. */
    embedUrl?: string;
    /** ID of the space the Smart Link is in. */
    spaceId?: string;
    version?: Version;
    _links?: SmartLinkLinks;
}

export interface FolderSingle {
    /** ID of the folder. */
    id?: string;
    /** The content type of the object. */
    type?: string;
    status?: ContentStatus;
    /** Title of the folder. */
    title?: string;
    /** ID of the parent content, or null if there is no parent content. */
    parentId?: string;
    parentType?: ParentContentType;
    /** Position of the folder within the given parent page tree. */
    position?: number;
    /** The account ID of the user who created this folder. */
    authorId?: string;
    /** The account ID of the user who owns this folder. */
    ownerId?: string;
    /** Date and time when the folder was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** ID of the space the folder is in. */
    spaceId?: string;
    version?: Version;
    _links?: FolderLinks;
}

export interface Ancestor {
    /** ID of the ancestor */
    id?: string;
    type?: AncestorType;
}

/** The type of ancestor. */
export type AncestorType = "page" | "whiteboard" | "database" | "embed" | "folder";

export interface Redaction {
    /** List of specific text ranges to redact within this section */
    redactions?: Array<RedactionPointer>;
}

export interface RedactionPointer {
    /**
     * JSON pointer indicating the exact location within the content structure 
     * where redaction should be applied. Points to the text node containing the content to redact.
     *
     */
    pointer: string;
    /**
     * Starting character index (zero-based) within the target text where redaction begins.
     *
     */
    from?: number;
    /**
     * Ending character index (zero-based) within the target text where redaction ends (exclusive).
     * Must be greater than or equal to 'from' value.
     *
     */
    to?: number;
    /**
     * Optional human-readable reason for the redaction. Used for audit trails and compliance documentation.
     *
     */
    reason?: string;
}

/**
 * Response containing details of all redactions that were applied to the content.
 * Each redaction includes a unique ID for restoration, except that code block redactions cannot be restored.
 *
 */
export interface RedactionResponse {
    body?: RedactionSectionResponse;
    title?: RedactionSectionResponse;
}

export interface RedactionSectionResponse {
    /** List of redactions that were applied to this section */
    redactions?: Array<RedactionPointerResponse>;
}

export interface RedactionPointerResponse {
    /** JSON pointer indicating where the redaction was applied */
    pointer?: string;
    /** Starting character index where redaction was applied */
    from?: number;
    /** Ending character index where redaction was applied */
    to?: number;
    /** Reason for the redaction */
    reason?: string;
    /**
     * Unique identifier for this redaction. Can be used to restore the redacted content later.
     *
     */
    redactionId?: string;
}

export interface SpaceSingle {
    /** ID of the space. */
    id?: string;
    /** Key of the space. */
    key?: string;
    /** Name of the space. */
    name?: string;
    type?: SpaceType;
    status?: SpaceStatus;
    /** The account ID of the user who created this space originally. */
    authorId?: string;
    /** Date and time when the space was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** ID of the space's homepage. */
    homepageId?: string;
    description?: SpaceDescription;
    icon?: SpaceIcon;
    labels?: { results?: Array<Label>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    properties?: { results?: Array<SpaceProperty>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    operations?: { results?: Array<Operation>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    permissions?: { results?: Array<SpacePermissionAssignment>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    _links?: SpaceLinks;
}

export interface SpaceBulk {
    /** ID of the space. */
    id?: string;
    /** Key of the space. */
    key?: string;
    /** Name of the space. */
    name?: string;
    type?: SpaceType;
    status?: SpaceStatus;
    /** The account ID of the user who created this space originally. */
    authorId?: string;
    /** Currently active alias for a Confluence space. */
    currentActiveAlias?: string;
    /** Date and time when the space was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** ID of the space's homepage. */
    homepageId?: string;
    description?: SpaceDescription;
    icon?: SpaceIcon;
    _links?: SpaceLinks;
}

/** Contains fields for each representation type requested. */
export interface SpaceDescription {
    plain?: BodyType;
    view?: BodyType;
}

/** The icon of the space */
export interface SpaceIcon {
    /** The path (relative to base URL) at which the space's icon can be retrieved. The format should be like `/wiki/download/...` or `/wiki/aa-avatar/...` */
    path?: string;
    /**
     * The path (relative to base URL) that can be used to retrieve a link to download the space icon. 3LO apps should use this link instead of the value provided
     * in the `path` property to retrieve the icon.
     *
     * Currently this field is only returned for `global` spaces and not `personal` spaces.
     *
     */
    apiDownloadLink?: string;
}

export interface SpacePermission {
    /** The identifier for the space permission. */
    id?: string;
    /** The display name for the space permission. */
    displayName?: string;
    /** Describes the space permission’s usage. */
    description?: string;
    /** The permissions required for this permission to be enabled. */
    requiredPermissionIds?: Array<string>;
}

export interface SpacePermissionAssignment {
    /** ID of the space permission. */
    id?: string;
    /** The entity the space permissions corresponds to. */
    principal?: { type?: "user" | "group" | "role"; id?: string };
    /** The operation the space permission corresponds to. */
    operation?: { key?: "use" | "create" | "read" | "update" | "delete" | "copy" | "move" | "export" | "purge" | "purge_version" | "administer" | "restore" | "create_space" | "restrict_content" | "archive"; targetType?: "page" | "blogpost" | "comment" | "attachment" | "whiteboard" | "database" | "embed" | "folder" | "space" | "application" | "userProfile" };
}

export interface SpaceRole {
    /** The identifier for the space role. */
    id?: string;
    type?: RoleType;
    /** The name for the space role. */
    name?: string;
    /** The description for the space role’s usage. */
    description?: string;
    /** The space permissions the space role is comprised of. */
    spacePermissions?: Array<string>;
}

export interface UpdateSpaceRoleResponse {
    /** Id of the space role */
    id?: string;
    type?: RoleType;
    /** Name of the space role */
    name?: string;
    /** Description for the space role */
    description?: string;
    /** Id of the task to update the space permissions associated with the space role */
    taskId?: string;
}

export interface DeleteSpaceRoleResponse {
    /** Id of the task to update the space permissions associated with the space role */
    taskId?: string;
}

export interface SpaceRoleAssignment {
    principal?: Principal;
    /** The role to which the principal is assigned. */
    roleId?: string;
}

/** The principal of the role assignment. */
export interface Principal {
    principalType?: PrincipalType;
    /** The principal ID. */
    principalId?: string;
}

/** The principal type. */
export type PrincipalType = "USER" | "GROUP" | "ACCESS_CLASS";
/** The role type. */
export type RoleType = "SYSTEM" | "CUSTOM";

export interface SpaceProperty {
    /** ID of the space property. */
    id?: string;
    /** Key of the space property. */
    key?: string;
    /** Value of the space property. */
    value?: Record<string, unknown>;
    /** RFC3339 compliant date time at which the property was created. */
    createdAt?: string;
    /** Atlassian account ID of the user that created the space property. */
    createdBy?: string;
    version?: { createdAt?: string; createdBy?: string; message?: string; number?: number };
}

export interface SpacePropertyCreateRequest {
    /** Key of the space property */
    key?: string;
    /** Value of the space property. */
    value?: Record<string, unknown>;
}

export interface SpacePropertyUpdateRequest {
    /** Key of the space property */
    key?: string;
    /** Value of the space property. */
    value?: Record<string, unknown>;
    /** New version number and associated message */
    version?: { number?: number; message?: string };
}

/** The type of space. */
export type SpaceType = "global" | "collaboration" | "knowledge_base" | "personal" | "system" | "onboarding" | "xflow_sample_space";
/** The status of the space. */
export type SpaceStatus = "current" | "archived";

export interface Task {
    /** ID of the task. */
    id?: string;
    /** Local ID of the task. This ID is local to the corresponding page or blog post. */
    localId?: string;
    /** ID of the space the task is in. */
    spaceId?: string;
    /** ID of the page the task is in. */
    pageId?: string;
    /** ID of the blog post the task is in. */
    blogPostId?: string;
    /** Status of the task. */
    status?: "complete" | "incomplete";
    body?: TaskBodySingle;
    /** Account ID of the user who created this task. */
    createdBy?: string;
    /** Account ID of the user to whom this task is assigned. */
    assignedTo?: string;
    /** Account ID of the user who completed this task. */
    completedBy?: string;
    /** Date and time when the task was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** Date and time when the task was updated. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    updatedAt?: string;
    /** Date and time when the task is due. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    dueAt?: string;
    /** Date and time when the task was completed. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    completedAt?: string;
}

/** The account type of the user. */
export type AccountType = "atlassian" | "app" | "customer" | "unknown";
/** The account status of the user. */
export type AccountStatus = "active" | "inactive" | "closed" | "unknown";

/** This object represents an icon. If used as a profilePicture, this may be returned as null, depending on the user's privacy setting. */
export interface Icon {
    path: string;
    isDefault: boolean;
}

export interface User {
    /** Display name of the user. */
    displayName?: string;
    /**
     * Time zone of the user. Depending on the user's privacy
     * setting, this may return null.
     */
    timeZone?: string;
    /** Space ID of the user's personal space. Returns null, if no personal space for the user. */
    personalSpaceId?: string;
    /** Whether the user is an external collaborator. */
    isExternalCollaborator?: boolean;
    accountStatus?: AccountStatus;
    /** Account ID of the user. */
    accountId?: string;
    /** The email address of the user. Depending on the user's privacy setting, this may return an empty string. */
    email?: string;
    accountType?: AccountType;
    /** Public name of the user. */
    publicName?: string;
    profilePicture?: Icon;
}

export interface Version {
    /** Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** Message associated with the current version. */
    message?: string;
    /** The version number. */
    number?: number;
    /** Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions. */
    minorEdit?: boolean;
    /** The account ID of the user who created this version. */
    authorId?: string;
}

export interface AttachmentVersion {
    /** Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** Message associated with the current version. */
    message?: string;
    /** The version number. */
    number?: number;
    /** Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions. */
    minorEdit?: boolean;
    /** The account ID of the user who created this version. */
    authorId?: string;
    attachment?: VersionedEntity;
}

export interface BlogPostVersion {
    /** Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** Message associated with the current version. */
    message?: string;
    /** The version number. */
    number?: number;
    /** Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions. */
    minorEdit?: boolean;
    /** The account ID of the user who created this version. */
    authorId?: string;
    blogpost?: VersionedEntity;
}

export interface PageVersion {
    /** Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** Message associated with the current version. */
    message?: string;
    /** The version number. */
    number?: number;
    /** Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions. */
    minorEdit?: boolean;
    /** The account ID of the user who created this version. */
    authorId?: string;
    page?: VersionedEntity;
}

export interface CustomContentVersion {
    /** Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** Message associated with the current version. */
    message?: string;
    /** The version number. */
    number?: number;
    /** Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions. */
    minorEdit?: boolean;
    /** The account ID of the user who created this version. */
    authorId?: string;
    custom?: VersionedEntity;
}

export interface CommentVersion {
    /** Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ". */
    createdAt?: string;
    /** Message associated with the current version. */
    message?: string;
    /** The version number. */
    number?: number;
    /** Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions. */
    minorEdit?: boolean;
    /** The account ID of the user who created this version. */
    authorId?: string;
    comment?: VersionedEntity;
}

export interface VersionedEntity {
    /** Title of the entity. */
    title?: string;
    /** ID of the entity. */
    id?: string;
    body?: BodyBulk;
}

/** The sort fields for attachments. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type AttachmentSortOrder = "created-date" | "-created-date" | "modified-date" | "-modified-date";
/** The sort fields for blog posts. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type BlogPostSortOrder = "id" | "-id" | "created-date" | "-created-date" | "modified-date" | "-modified-date";
/** The sort fields for comments. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type CommentSortOrder = "created-date" | "-created-date" | "modified-date" | "-modified-date";
/** The sort fields for content properties. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type ContentPropertySortOrder = "key" | "-key";
/** The sort fields for hierarchical content types. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type ContentSortOrder = "created-date" | "-created-date" | "id" | "-id" | "modified-date" | "-modified-date" | "child-position" | "-child-position" | "title" | "-title";
/** The sort fields for labels. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type LabelSortOrder = "created-date" | "-created-date" | "id" | "-id" | "name" | "-name";
/** The sort fields for child pages. The default sort direction is ascending by child-position. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type ChildPageSortOrder = "created-date" | "-created-date" | "id" | "-id" | "child-position" | "-child-position" | "modified-date" | "-modified-date";
/** The sort fields for child custom content. The default sort direction is ascending by id. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type ChildCustomContentSortOrder = "created-date" | "-created-date" | "id" | "-id" | "modified-date" | "-modified-date";
/** The sort fields for custom content. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type CustomContentSortOrder = "id" | "-id" | "created-date" | "-created-date" | "modified-date" | "-modified-date" | "title" | "-title";
/** The sort fields for pages. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type PageSortOrder = "id" | "-id" | "created-date" | "-created-date" | "modified-date" | "-modified-date" | "title" | "-title";
/** The sort fields for spaces. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type SpaceSortOrder = "id" | "-id" | "key" | "-key" | "name" | "-name";
/** The sort fields for versions. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`. */
export type VersionSortOrder = "modified-date" | "-modified-date";
/** Inline comment resolution status */
export type InlineCommentResolutionStatus = "open" | "reopened" | "resolved" | "dangling";

export interface InlineCommentProperties {
    /** Property value used to reference the highlighted element in DOM. */
    inlineMarkerRef?: string;
    /** Text that is highlighted. */
    inlineOriginalSelection?: string;
}

export interface PageCommentModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the page the comment is in. */
    pageId?: string;
    version?: Version;
    body?: BodyBulk;
    _links?: CommentLinks;
}

export interface PageInlineCommentModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the page the comment is in. */
    pageId?: string;
    version?: Version;
    body?: BodyBulk;
    resolutionStatus?: InlineCommentResolutionStatus;
    properties?: InlineCommentProperties;
    _links?: CommentLinks;
}

export interface BlogPostCommentModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the blog post the comment is in. */
    blogPostId?: string;
    version?: Version;
    body?: BodyBulk;
    _links?: CommentLinks;
}

export interface BlogPostInlineCommentModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the blog post the comment is in. */
    blogPostId?: string;
    version?: Version;
    body?: BodyBulk;
    resolutionStatus?: InlineCommentResolutionStatus;
    properties?: InlineCommentProperties;
    _links?: CommentLinks;
}

export interface ChildrenCommentModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the parent comment the child comment is in. */
    parentCommentId?: string;
    version?: Version;
    body?: BodyBulk;
    _links?: CommentLinks;
}

export interface InlineCommentChildrenModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the parent comment the child comment is in. */
    parentCommentId?: string;
    version?: Version;
    body?: BodyBulk;
    resolutionStatus?: InlineCommentResolutionStatus;
    properties?: InlineCommentProperties;
    _links?: CommentLinks;
}

export interface AttachmentCommentModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the attachment containing the comment. */
    attachmentId?: string;
    version?: Version;
    body?: BodySingle;
    _links?: CommentLinks;
}

export interface CustomContentCommentModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the custom content containing the comment. */
    customContentId?: string;
    version?: Version;
    body?: BodySingle;
    _links?: CommentLinks;
}

export interface FooterCommentModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the blog post containing the comment if the comment is on a blog post. */
    blogPostId?: string;
    /** ID of the page containing the comment if the comment is on a page. */
    pageId?: string;
    /** ID of the attachment containing the comment if the comment is on an attachment. */
    attachmentId?: string;
    /** ID of the custom content containing the comment if the comment is on a custom content. */
    customContentId?: string;
    /** ID of the parent comment if the comment is a reply. */
    parentCommentId?: string;
    version?: Version;
    properties?: { results?: Array<ContentProperty>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    operations?: { results?: Array<Operation>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    likes?: { results?: Array<Like>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    versions?: { results?: Array<Version>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    body?: BodySingle;
    _links?: CommentLinks;
}

export interface InlineCommentModel {
    /** ID of the comment. */
    id?: string;
    status?: ContentStatus;
    /** Title of the comment. */
    title?: string;
    /** ID of the blog post containing the comment if the comment is on a blog post. */
    blogPostId?: string;
    /** ID of the page containing the comment if the comment is on a page. */
    pageId?: string;
    /** ID of the parent comment if the comment is a reply. */
    parentCommentId?: string;
    version?: Version;
    body?: BodySingle;
    /** Atlassian Account ID of last person who modified the resolve state of the comment. Null until comment is resolved or reopened. */
    resolutionLastModifierId?: string;
    /** Timestamp of the last modification to the comment's resolution status. Null until comment is resolved or reopened. */
    resolutionLastModifiedAt?: string;
    resolutionStatus?: InlineCommentResolutionStatus;
    properties?: { results?: Array<ContentProperty>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks; inlineMarkerRef?: string; inlineOriginalSelection?: string };
    operations?: { results?: Array<Operation>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    likes?: { results?: Array<Like>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    versions?: { results?: Array<Version>; meta?: OptionalFieldMeta; _links?: OptionalFieldLinks };
    _links?: CommentLinks;
}

export interface CreateFooterCommentModel {
    /** ID of the containing blog post, if intending to create a top level footer comment. Do not provide if creating a reply. */
    blogPostId?: string;
    /** ID of the containing page, if intending to create a top level footer comment. Do not provide if creating a reply. */
    pageId?: string;
    /** ID of the parent comment, if intending to create a reply. Do not provide if creating a top level comment. */
    parentCommentId?: string;
    /** ID of the attachment, if intending to create a comment against an attachment. */
    attachmentId?: string;
    /** ID of the custom content, if intending to create a comment against a custom content. */
    customContentId?: string;
    body?: CommentBodyWrite | CommentNestedBodyWrite;
}

export interface CreateInlineCommentModel {
    /** ID of the containing blog post, if intending to create a top level footer comment. Do not provide if creating a reply. */
    blogPostId?: string;
    /** ID of the containing page, if intending to create a top level footer comment. Do not provide if creating a reply. */
    pageId?: string;
    /** ID of the parent comment, if intending to create a reply. Do not provide if creating a top level comment. */
    parentCommentId?: string;
    body?: CommentBodyWrite | CommentNestedBodyWrite;
    /** Object describing the text to highlight on the page/blog post. Only applicable for top level inline comments (not replies) and required in that case. */
    inlineCommentProperties?: { textSelection?: string; textSelectionMatchCount?: number; textSelectionMatchIndex?: number };
}

export interface UpdateFooterCommentModel {
    version?: { number?: number; message?: string };
    body?: CommentBodyWrite | CommentNestedBodyWrite;
}

export interface UpdateInlineCommentModel {
    version?: { number?: number; message?: string };
    body?: CommentBodyWrite | CommentNestedBodyWrite;
    /**
     * Resolved state of the comment. Set to true to resolve the comment, set to false to reopen it. If
     * matching the existing state (i.e. true -> resolved or false -> open/reopened) , no change will occur. A dangling
     * comment cannot be updated.
     */
    resolved?: boolean;
}

export interface AbstractPageLinks {
    /** Web UI link of the content. */
    webui?: string;
    /** Edit UI link of the content. */
    editui?: string;
    /** Web UI link of the content. */
    tinyui?: string;
}

export interface AttachmentLinks {
    /** Web UI link of the content. */
    webui?: string;
    /** Download link of the content. */
    download?: string;
}

export interface CustomContentLinks {
    /** Web UI link of the content. */
    webui?: string;
}

export interface CommentLinks {
    /** Web UI link of the content. */
    webui?: string;
}

export interface DatabaseLinks {
    /** Web UI link of the content. */
    webui?: string;
}

export interface FolderLinks {
    /** Web UI link of the content. */
    webui?: string;
}

export interface SmartLinkLinks {
    /** Web UI link of the content. */
    webui?: string;
}

export interface SpaceLinks {
    /** Web UI link of the space. */
    webui?: string;
}

export interface WhiteboardLinks {
    /** Web UI link of the content. */
    webui?: string;
    /** Edit UI link of the content. */
    editui?: string;
}

/** Details about data policies. */
export interface DataPolicyMetadata {
    /** Whether the workspace contains any content blocked for (inaccessible to) the requesting client application. */
    readonly anyContentBlocked?: boolean;
}

export interface DataPolicySpace {
    /** ID of the space. */
    id?: string;
    /** Key of the space. */
    key?: string;
    /** Name of the space. */
    name?: string;
    description?: SpaceDescription;
    dataPolicy?: { readonly anyContentBlocked?: boolean };
    icon?: SpaceIcon;
    _links?: SpaceLinks;
}

export interface OptionalFieldMeta {
    /** Indicates if there are more available results that can be fetched. */
    hasMore?: boolean;
    /** A token that can be used in the query parameter of the endpoint returned in the `_links` property to retrieve the next set of results. */
    cursor?: string;
}

export interface OptionalFieldLinks {
    /** A relative URL that can be used to fetch results beyond what this include parameter retrieves. */
    self?: string;
}

export interface MultiEntityLinks {
    /**
     * Used for pagination. Contains the relative URL for the next set of results, using a cursor query parameter.
     * This property will not be present if there is no additional data available.
     */
    next?: string;
    /** Base url of the Confluence site. */
    base?: string;
}

/**
 * A unit of [data classification](https://support.atlassian.com/security-and-access-policies/docs/what-is-data-classification/) defined by an organiation. 
 * A classification level may be associated with specific storage and handling requirements or expectations.
 */
export interface ClassificationLevel {
    /** The ID of the classification level. */
    id?: string;
    /** The status of the classification level. */
    status?: ClassificationLevelStatus;
    /** The order of the classification level object. */
    order?: number;
    /** The name of the classification level object. */
    name?: string;
    /** The description of the classification level object. */
    description?: string;
    /** The guideline of the classification level object. */
    guideline?: string;
    /** The color of the classification level object. */
    color?: ClassificationLevelColor;
}

export type ClassificationLevelColor = "RED" | "RED_BOLD" | "ORANGE" | "YELLOW" | "GREEN" | "BLUE" | "NAVY" | "TEAL" | "PURPLE" | "GREY" | "LIME";
export type ClassificationLevelStatus = "DRAFT" | "PUBLISHED" | "ARCHIVED";

export interface ErrorResponse {
    errorMessages?: Array<string>;
    errors?: Record<string, string>;
    status?: number;
    message?: string;
}

export interface RateLimitError {
    message?: string;
    retryAfter?: number;
}
