/**
 * Jira Cloud REST API v3
 *
 * This file is generated by @forge-clients/generator.
 * Run `pnpm generate` (or `pnpm generate --only jira-v3`) to regenerate.
 *
 * - types.gen.ts  — TypeScript interfaces for all request/response schemas
 * - sdk.gen.ts    — Named, tree-shakeable async functions for every endpoint
 *
 * DO NOT hand-edit this file — it will be overwritten on next generation.
 */

// All TypeScript types (interfaces, enums) — zero runtime cost, erased at build time
export type * from './types.gen.js';

// All named SDK functions — individually tree-shakeable
// Import only what you need: import { getIssue } from '@forge-clients/jira/v3'
export * from './sdk.gen.js';
