// Generated by @forge-clients/generator — DO NOT EDIT
// Source: Jira Software Cloud REST API
/* eslint-disable */
// prettier-ignore
export interface AvatarUrlsBean {
    /** The URL of the item's 16x16 pixel avatar. */
    16x16?: string;
    /** The URL of the item's 24x24 pixel avatar. */
    24x24?: string;
    /** The URL of the item's 32x32 pixel avatar. */
    32x32?: string;
    /** The URL of the item's 48x48 pixel avatar. */
    48x48?: string;

/** Details about a board. */
export interface Board {
    readonly admins?: { groups?: Array<{ name?: string; self?: string }>; users?: Array<{ accountId?: string; active?: boolean; avatarUrls?: { 16x16?: string; 24x24?: string; 32x32?: string; 48x48?: string }; displayName?: string; key?: string; name?: string; self?: string }> };
    /** Whether the board can be edited. */
    readonly canEdit?: boolean;
    /** Whether the board is selected as a favorite. */
    readonly favourite?: boolean;
    /** The ID of the board. */
    id?: number;
    /** Whether the board is private. */
    readonly isPrivate?: boolean;
    /** The container that the board is located in. */
    location?: { avatarURI?: string; displayName?: string; name?: string; projectId?: number; projectKey?: string; projectName?: string; projectTypeKey?: string; userAccountId?: string; userId?: number };
    /** The name of the board. */
    name?: string;
    /** The URL of the board. */
    readonly self?: string;
    /** The type the board. */
    type?: string;

/** The users and groups who own the board. */
export interface BoardAdminsBean {
    groups?: Array<{ name?: string; self?: string }>;
    users?: Array<{ accountId?: string; active?: boolean; avatarUrls?: { 16x16?: string; 24x24?: string; 32x32?: string; 48x48?: string }; displayName?: string; key?: string; name?: string; self?: string }>;

export interface BoardConfigBean {
    columnConfig?: { columns?: Array<{ max?: number; min?: number; name?: string; statuses?: Array<{ id?: string; self?: string }> }>; constraintType?: string };
    estimation?: { field?: { displayName?: string; fieldId?: string }; type?: string };
    filter?: { id?: string; self?: string };
    id?: number;
    location?: { projectKeyOrId?: string; type?: "project" | "user" };
    name?: string;
    ranking?: { rankCustomFieldId?: number };
    self?: string;
    subQuery?: { query?: string };
    type?: string;
}

export interface BoardCreateBean {
    filterId?: number;
    location?: { projectKeyOrId?: string; type?: "project" | "user" };
    name?: string;
    type?: "kanban" | "scrum" | "agility";
}

export interface BoardFilterBean {
    id?: number;
    name?: string;
    self?: string;
}

/** The container that the board is located in. */
export interface BoardLocationBean {
    avatarURI?: string;
    displayName?: string;
    name?: string;
    projectId?: number;
    projectKey?: string;
    projectName?: string;
    projectTypeKey?: string;
    userAccountId?: string;
    userId?: number;
}

/** A change item. */
export interface ChangeDetails {
    /** The name of the field changed. */
    readonly field?: string;
    /** The ID of the field changed. */
    readonly fieldId?: string;
    /** The type of the field changed. */
    readonly fieldtype?: string;
    /** The details of the original value. */
    readonly from?: string;
    /** The details of the original value as a string. */
    readonly fromString?: string;
    /** The details of the new value. */
    readonly to?: string;
    /** The details of the new value as a string. */
    readonly toString?: string;
}

/** A log of changes made to issue fields. Changelogs related to workflow associations are currently being deprecated. */
export interface Changelog {
    /** The user who made the change. */
    readonly author?: { accountId?: string; readonly accountType?: string; readonly active?: boolean; readonly avatarUrls?: { 16x16?: string; 24x24?: string; 32x32?: string; 48x48?: string }; readonly displayName?: string; readonly emailAddress?: string; readonly key?: string; readonly name?: string; readonly self?: string; readonly timeZone?: string };
    /** The date on which the change took place. */
    readonly created?: string;
    /** The history metadata associated with the changed. */
    readonly historyMetadata?: Record<string, unknown>;
    /** The ID of the changelog. */
    readonly id?: string;
    /** The list of items changed. */
    readonly items?: Array<{ readonly field?: string; readonly fieldId?: string; readonly fieldtype?: string; readonly from?: string; readonly fromString?: string; readonly to?: string; readonly toString?: string }>;

export interface ColorBean {
    key?: "color_1" | "color_2" | "color_3" | "color_4" | "color_5" | "color_6" | "color_7" | "color_8" | "color_9" | "color_10" | "color_11" | "color_12" | "color_13" | "color_14";
}

export interface ColumnBean {
    max?: number;
    min?: number;
    name?: string;
    statuses?: Array<{ id?: string; self?: string }>;
}

export interface ColumnConfigBean {
    columns?: Array<{ max?: number; min?: number; name?: string; statuses?: Array<{ id?: string; self?: string }> }>;
    constraintType?: string;
}

export interface Entry {
    errors?: Array<string>;
    issueId?: number;
    issueKey?: string;
    status?: number;
}

export interface EpicRankRequestBean {
    rankAfterEpic?: string;
    rankBeforeEpic?: string;
    rankCustomFieldId?: number;
}

export interface EpicUpdateBean {
    color?: { key?: "color_1" | "color_2" | "color_3" | "color_4" | "color_5" | "color_6" | "color_7" | "color_8" | "color_9" | "color_10" | "color_11" | "color_12" | "color_13" | "color_14" };
    done?: boolean;
    name?: string;
    summary?: string;
}

export interface EstimationConfigBean {
    field?: { displayName?: string; fieldId?: string };
    type?: string;
}

export interface EstimationConfigurationBean {
    localisedDescription?: string;
    localisedName?: string;
    value?: "STORY_POINTS" | "ORIGINAL_ESTIMATE";
}

export interface EstimationFieldBean {
    displayName?: string;
    fieldId?: string;
}

export interface FeatureBean {
    boardFeature?: "SIMPLE_ROADMAP" | "BACKLOG" | "SPRINTS" | "CALENDAR" | "DEVTOOLS" | "REPORTS" | "ESTIMATION" | "PAGES" | "CODE" | "SECURITY" | "REQUESTS" | "INCIDENTS" | "RELEASES" | "DEPLOYMENTS" | "ISSUE_NAVIGATOR" | "ON_CALL_SCHEDULE" | "BOARD" | "GOALS" | "LIST_VIEW";
    boardId?: number;
    featureId?: string;
    featureType?: "BASIC" | "ESTIMATION";
    imageUri?: string;
    learnMoreArticleId?: string;
    learnMoreLink?: string;
    localisedDescription?: string;
    localisedGroup?: string;
    localisedName?: string;
    permissibleEstimationTypes?: Array<{ localisedDescription?: string; localisedName?: string; value?: "STORY_POINTS" | "ORIGINAL_ESTIMATE" }>;
    state?: "ENABLED" | "DISABLED" | "COMING_SOON";
    toggleLocked?: boolean;
}

export interface FeatureResponseBean {
    features?: Array<{ boardFeature?: "SIMPLE_ROADMAP" | "BACKLOG" | "SPRINTS" | "CALENDAR" | "DEVTOOLS" | "REPORTS" | "ESTIMATION" | "PAGES" | "CODE" | "SECURITY" | "REQUESTS" | "INCIDENTS" | "RELEASES" | "DEPLOYMENTS" | "ISSUE_NAVIGATOR" | "ON_CALL_SCHEDULE" | "BOARD" | "GOALS" | "LIST_VIEW"; boardId?: number; featureId?: string; featureType?: "BASIC" | "ESTIMATION"; imageUri?: string; learnMoreArticleId?: string; learnMoreLink?: string; localisedDescription?: string; localisedGroup?: string; localisedName?: string; permissibleEstimationTypes?: Array<{ localisedDescription?: string; localisedName?: string; value?: "STORY_POINTS" | "ORIGINAL_ESTIMATE" }>; state?: "ENABLED" | "DISABLED" | "COMING_SOON"; toggleLocked?: boolean }>;
}

export interface FeatureToggleRequestBean {
    boardId?: number;
    enabling?: boolean;
    feature?: string;
}

export interface FieldEditBean {
    value?: string;
}

/** The metadata describing an issue field. */
export interface FieldMetadata {
    /** The list of values allowed in the field. */
    readonly allowedValues?: Array<Record<string, unknown>>;
    /** The URL that can be used to automatically complete the field. */
    readonly autoCompleteUrl?: string;
    /** The configuration properties. */
    readonly configuration?: Record<string, Record<string, unknown>>;
    /** The default value of the field. */
    readonly defaultValue?: Record<string, unknown>;
    /** Whether the field has a default value. */
    readonly hasDefaultValue?: boolean;
    /** The key of the field. */
    readonly key: string;
    /** The name of the field. */
    readonly name: string;
    /** The list of operations that can be performed on the field. */
    readonly operations: Array<string>;
    /** Whether the field is required. */
    readonly required: boolean;
    /** The data type of the field. */
    readonly schema: { readonly configuration?: Record<string, Record<string, unknown>>; readonly custom?: string; readonly customId?: number; readonly items?: string; readonly system?: string; readonly type: string };
}

export interface GroupBean {
    name?: string;
    self?: string;
}

/** Details of issue history metadata. */
export type HistoryMetadata = Record<string, unknown>;
/** Details of user or system associated with a issue history metadata item. */
export type HistoryMetadataParticipant = Record<string, unknown>;

export interface IncludedFields {
    actuallyIncluded?: Array<string>;
    excluded?: Array<string>;
    included?: Array<string>;
}

export interface IssueAssignRequestBean {
    issues?: Array<string>;
}

/** Details about an issue. */
export interface IssueBean {
    /** Details of changelogs associated with the issue. */
    readonly changelog?: { readonly histories?: Array<{ readonly author?: { accountId?: string; readonly accountType?: string; readonly active?: boolean; readonly avatarUrls?: { 16x16?: string; 24x24?: string; 32x32?: string; 48x48?: string }; readonly displayName?: string; readonly emailAddress?: string; readonly key?: string; readonly name?: string; readonly self?: string; readonly timeZone?: string }; readonly created?: string; readonly historyMetadata?: Record<string, unknown>; readonly id?: string; readonly items?: Array<{ readonly field?: string; readonly fieldId?: string; readonly fieldtype?: string; readonly from?: string; readonly fromString?: string; readonly to?: string; readonly toString?: string }> }>; readonly maxResults?: number; readonly startAt?: number; readonly total?: number };
    /** The metadata for the fields on the issue that can be amended. */
    readonly editmeta?: { readonly fields?: Record<string, { readonly allowedValues?: Array<Record<string, unknown>>; readonly autoCompleteUrl?: string; readonly configuration?: Record<string, Record<string, unknown>>; readonly defaultValue?: Record<string, unknown>; readonly hasDefaultValue?: boolean; readonly key: string; readonly name: string; readonly operations: Array<string>; readonly required: boolean; readonly schema: { readonly configuration?: Record<string, Record<string, unknown>>; readonly custom?: string; readonly customId?: number; readonly items?: string; readonly system?: string; readonly type: string } }> };
    /** Expand options that include additional issue details in the response. */
    readonly expand?: string;
    fields?: Record<string, Record<string, unknown>>;
    fieldsToInclude?: { actuallyIncluded?: Array<string>; excluded?: Array<string>; included?: Array<string> };
    /** The ID of the issue. */
    readonly id?: string;
    /** The key of the issue. */
    readonly key?: string;
    /** The ID and name of each field present on the issue. */
    readonly names?: Record<string, string>;
    /** The operations that can be performed on the issue. */
    readonly operations?: Operations;
    /** Details of the issue properties identified in the request. */
    readonly properties?: Record<string, Record<string, unknown>>;
    /** The rendered value of each field present on the issue. */
    readonly renderedFields?: Record<string, Record<string, unknown>>;
    /** The schema describing each field present on the issue. */
    readonly schema?: Record<string, { readonly configuration?: Record<string, Record<string, unknown>>; readonly custom?: string; readonly customId?: number; readonly items?: string; readonly system?: string; readonly type: string }>;
    /** The URL of the issue details. */
    readonly self?: string;
    /** The transitions that can be performed on the issue. */
    readonly transitions?: Array<Record<string, unknown>>;
    /** The versions of each field on the issue. */
    readonly versionedRepresentations?: Record<string, Record<string, Record<string, unknown>>>;

export interface IssueRankRequestBean {
    issues?: Array<string>;
    rankAfterIssue?: string;
    rankBeforeIssue?: string;
    rankCustomFieldId?: number;
}

/** Details of an issue transition. */
export type IssueTransition = Record<string, unknown>;

/** A list of editable field details. */
export interface IssueUpdateMetadata {
    readonly fields?: Record<string, { readonly allowedValues?: Array<Record<string, unknown>>; readonly autoCompleteUrl?: string; readonly configuration?: Record<string, Record<string, unknown>>; readonly defaultValue?: Record<string, unknown>; readonly hasDefaultValue?: boolean; readonly key: string; readonly name: string; readonly operations: Array<string>; readonly required: boolean; readonly schema: { readonly configuration?: Record<string, Record<string, unknown>>; readonly custom?: string; readonly customId?: number; readonly items?: string; readonly system?: string; readonly type: string } }>;
}

/** The schema of a field. */
export interface JsonTypeBean {
    /** If the field is a custom field, the configuration of the field. */
    readonly configuration?: Record<string, Record<string, unknown>>;
    /** If the field is a custom field, the URI of the field. */
    readonly custom?: string;
    /** If the field is a custom field, the custom ID of the field. */
    readonly customId?: number;
    /** When the data type is an array, the name of the field items within the array. */
    readonly items?: string;
    /** If the field is a system field, the name of the field. */
    readonly system?: string;
    /** The data type of the field. */
    readonly type: string;
}

/** Details a link group, which defines issue operations. */
export interface LinkGroup {
    groups?: Array<LinkGroup>;
    /** Details about the operations available in this version. */
    header?: { href?: string; iconClass?: string; id?: string; label?: string; styleClass?: string; title?: string; weight?: number };
    id?: string;
    links?: Array<{ href?: string; iconClass?: string; id?: string; label?: string; styleClass?: string; title?: string; weight?: number }>;
    styleClass?: string;
    weight?: number;
}

export interface LocationBean {
    projectKeyOrId?: string;
    type?: "project" | "user";
}

/** Details of the operations that can be performed on the issue. */
export type Operations = Record<string, unknown>;

export interface PageBeanBoard {
    isLast?: boolean;
    maxResults?: number;
    startAt?: number;
    total?: number;
    values?: Array<{ readonly admins?: { groups?: Array<{ name?: string; self?: string }>; users?: Array<{ accountId?: string; active?: boolean; avatarUrls?: { 16x16?: string; 24x24?: string; 32x32?: string; 48x48?: string }; displayName?: string; key?: string; name?: string; self?: string }> }; readonly canEdit?: boolean; readonly favourite?: boolean; id?: number; readonly isPrivate?: boolean; location?: { avatarURI?: string; displayName?: string; name?: string; projectId?: number; projectKey?: string; projectName?: string; projectTypeKey?: string; userAccountId?: string; userId?: number }; name?: string; readonly self?: string; type?: string }>;

export interface PageBeanBoardFilterBean {
    isLast?: boolean;
    maxResults?: number;
    startAt?: number;
    total?: number;
    values?: Array<{ id?: number; name?: string; self?: string }>;
}

export interface PageBeanQuickFilterBean {
    isLast?: boolean;
    maxResults?: number;
    startAt?: number;
    total?: number;
    values?: Array<{ boardId?: number; description?: string; id?: number; jql?: string; name?: string; position?: number }>;
}

/** A page of changelogs. */
export interface PageOfChangelogs {
    /** The list of changelogs. */
    readonly histories?: Array<{ readonly author?: { accountId?: string; readonly accountType?: string; readonly active?: boolean; readonly avatarUrls?: { 16x16?: string; 24x24?: string; 32x32?: string; 48x48?: string }; readonly displayName?: string; readonly emailAddress?: string; readonly key?: string; readonly name?: string; readonly self?: string; readonly timeZone?: string }; readonly created?: string; readonly historyMetadata?: Record<string, unknown>; readonly id?: string; readonly items?: Array<{ readonly field?: string; readonly fieldId?: string; readonly fieldtype?: string; readonly from?: string; readonly fromString?: string; readonly to?: string; readonly toString?: string }> }>;
    /** The maximum number of results that could be on the page. */
    readonly maxResults?: number;
    /** The index of the first item returned on the page. */
    readonly startAt?: number;
    /** The number of results on the page. */
    readonly total?: number;

export interface PartialSuccessBean {
    entries?: Array<{ errors?: Array<string>; issueId?: number; issueKey?: string; status?: number }>;
}

/** Details about a project. */
export interface ProjectDetails {
    /** The URLs of the project's avatars. */
    readonly avatarUrls?: { 16x16?: string; 24x24?: string; 32x32?: string; 48x48?: string };
    /** The ID of the project. */
    id?: string;
    /** The key of the project. */
    readonly key?: string;
    /** The name of the project. */
    readonly name?: string;
    /** The category the project belongs to. */
    readonly projectCategory?: { readonly description?: string; readonly id?: string; readonly name?: string; readonly self?: string };
    /** The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project. */
    readonly projectTypeKey?: "software" | "service_desk" | "business";
    /** The URL of the project details. */
    readonly self?: string;
    /** Whether or not the project is simplified. */
    readonly simplified?: boolean;

export interface QuickFilterBean {
    boardId?: number;
    description?: string;
    id?: number;
    jql?: string;
    name?: string;
    position?: number;
}

export interface RankingConfigBean {
    rankCustomFieldId?: number;
}

export interface RelationBean {
    id?: string;
    self?: string;
}

export interface ReportBean {
}

export interface ReportsResponseBean {
    reports?: Array<Record<string, unknown>>;
}

/** The projects the item is associated with. Indicated for items associated with [next-gen projects](https://confluence.atlassian.com/x/loMyO). */
export type Scope = Record<string, unknown>;

/** The result of a JQL search. */
export interface SearchResults {
    /** Expand options that include additional search result details in the response. */
    readonly expand?: string;
    /** The list of issues found by the search. */
    readonly issues?: Array<IssueBean>;
    /** The maximum number of results that could be on the page. */
    readonly maxResults?: number;
    /** The ID and name of each field in the search results. */
    readonly names?: Record<string, string>;
    /** The schema describing the field types in the search results. */
    readonly schema?: Record<string, { readonly configuration?: Record<string, Record<string, unknown>>; readonly custom?: string; readonly customId?: number; readonly items?: string; readonly system?: string; readonly type: string }>;
    /** The index of the first item returned on the page. */
    readonly startAt?: number;
    /** The number of results on the page. */
    readonly total?: number;
    /** Any warnings related to the JQL query. */
    readonly warningMessages?: Array<string>;
}

/** Details about the operations available in this version. */
export interface SimpleLink {
    href?: string;
    iconClass?: string;
    id?: string;
    label?: string;
    styleClass?: string;
    title?: string;
    weight?: number;
}

export interface SprintBean {
    completeDate?: string;
    createdDate?: string;
    endDate?: string;
    goal?: string;
    id?: number;
    name?: string;
    originBoardId?: number;
    self?: string;
    startDate?: string;
    state?: string;
}

export interface SprintCreateBean {
    endDate?: string;
    goal?: string;
    name?: string;
    originBoardId?: number;
    startDate?: string;
}

export interface SprintSwapBean {
    sprintToSwapWith?: number;
}

/** A status category. */
export type StatusCategory = Record<string, unknown>;
/** A status. */
export type StatusDetails = Record<string, unknown>;

export interface StringList {
}

export interface SubqueryBean {
    query?: string;
}

/** A project category. */
export interface UpdatedProjectCategory {
    /** The name of the project category. */
    readonly description?: string;
    /** The ID of the project category. */
    readonly id?: string;
    /** The description of the project category. */
    readonly name?: string;
    /** The URL of the project category. */
    readonly self?: string;
}

export interface UserBean {
    /** The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. */
    accountId?: string;
    /** Whether the user is active. */
    active?: boolean;
    /** The avatars of the user. */
    avatarUrls?: { 16x16?: string; 24x24?: string; 32x32?: string; 48x48?: string };
    /** The display name of the user. Depending on the user’s privacy setting, this may return an alternative value. */
    displayName?: string;
    /**
     * This property is deprecated in favor of `accountId` because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.  
     * The key of the user.
     */
    key?: string;
    /**
     * This property is deprecated in favor of `accountId` because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.  
     * The username of the user.
     */
    name?: string;
    /** The URL of the user. */
    self?: string;

export interface UserBeanAvatarUrls {
    /** The URL of the user's 16x16 pixel avatar. */
    16x16?: string;
    /** The URL of the user's 24x24 pixel avatar. */
    24x24?: string;
    /** The URL of the user's 32x32 pixel avatar. */
    32x32?: string;
    /** The URL of the user's 48x48 pixel avatar. */
    48x48?: string;

/**
 * User details permitted by the user's Atlassian Account privacy settings. However, be aware of these exceptions:
 *
 *  *  User record deleted from Atlassian: This occurs as the result of a right to be forgotten request. In this case, `displayName` provides an indication and other parameters have default values or are blank (for example, email is blank).
 *  *  User record corrupted: This occurs as a results of events such as a server import and can only happen to deleted users. In this case, `accountId` returns *unknown* and all other parameters have fallback values.
 *  *  User record unavailable: This usually occurs due to an internal service outage. In this case, all parameters have fallback values.
 */
export interface UserDetails {
    /** The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. */
    accountId?: string;
    /** The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user) */
    readonly accountType?: string;
    /** Whether the user is active. */
    readonly active?: boolean;
    /** The avatars of the user. */
    readonly avatarUrls?: { 16x16?: string; 24x24?: string; 32x32?: string; 48x48?: string };
    /** The display name of the user. Depending on the user’s privacy settings, this may return an alternative value. */
    readonly displayName?: string;
    /** The email address of the user. Depending on the user’s privacy settings, this may be returned as null. */
    readonly emailAddress?: string;
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    readonly key?: string;
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    readonly name?: string;
    /** The URL of the user. */
    readonly self?: string;
    /** The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null. */
    readonly timeZone?: string;

/**
 * An association type referencing issues in Jira.
 *
 */
export interface IssueIdOrKeysAssociation {
    /**
     * Defines the association type.
     *
     */
    associationType: "issueKeys" | "issueIdOrKeys";
    /**
     * The Jira issue keys or IDs to associate the entity with.
     *
     * The number of values counted across all associationTypes must not exceed a limit of 500.
     *
     */
    values: Array<string>;
}

/**
 * An association type referencing service ID or keys.
 *
 */
export interface ServiceIdOrKeysAssociation {
    /**
     * Defines the association type.
     *
     */
    associationType: "serviceIdOrKeys";
    /**
     * The service ID or keys to associate the entity with.
     *
     * The number of values counted across all associationTypes must not exceed a limit of 500.
     *
     */
    values: Array<string>;
}

/**
 * An association type referencing another entity
 *
 */
export interface EntityAssociation {
    /**
     * Defines the association type. Currently supported entities can be found in this field's value enums list.
     *
     */
    associationType: "commit" | "repository";
    /**
     * The entity keys that represent the entities to be associated.
     * The number of values counted across all associationTypes must not exceed a limit of 500.
     *
     */
    values: Array<{ commitHash: string; repositoryId: string }>;
}

export interface ErrorResponse {
    errorMessages?: Array<string>;
    errors?: Record<string, string>;
    status?: number;
    message?: string;
}

export interface RateLimitError {
    message?: string;
    retryAfter?: number;
}

}

}

}

}

}

}

}

}

}

}

}
