import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  // DTS generated by tsup's bundled rollup-plugin-dts.
  // @forge/api and @forge/bridge are marked external so tsup doesn't try to
  // resolve them at build time (they are Forge runtime-only packages).
  dts: false,
  sourcemap: true,
  clean: true,
  splitting: false,
  external: ['@forge/api', '@forge/bridge'],
});
