/**
 * Confluence Cloud REST API v1
 *
 * Generated by @forge-clients/generator. DO NOT EDIT.
 * Run `pnpm generate --only confluence-v1` to regenerate.
 *
 * - types.gen.ts  TypeScript interfaces for all request/response schemas
 * - sdk.gen.ts    Named, tree-shakeable async functions for every endpoint
 */

// All TypeScript types — zero runtime cost, erased at build time
export * from './types.gen.js';

// All named SDK functions — individually tree-shakeable
export * from './sdk.gen.js';
