// Generated by @forge-clients/generator — DO NOT EDIT
// Source: Confluence Cloud REST API v1
/* eslint-disable */
// prettier-ignore
export interface AccountId {
    accountId: string;
}

export interface AccountIdEmailRecord {
    accountId: string;
    email: string;
}

export type AccountIdEmailRecordArray = Array<AccountIdEmailRecord>;

export interface AffectedObject {
    name: string;
    objectType: string;
}

export interface AsyncId {
    asyncId: string;
}

export type AsyncIdArray = Array<AsyncId>;

export interface AttachmentUpdate {
    /**
     * The attachment version. Set this to the current version number of the
     * attachment. Note, the version number only needs to be incremented when
     * updating the actual attachment, not its properties.
     */
    version: { number: number };
    /** The ID of the attachment to be updated. */
    id: string;
    /** Set this to `attachment`. */
    type: "attachment";
    /** The updated name of the attachment. */
    title?: string;
    metadata?: { mediaType?: string; comment?: string };
    /** The new content to attach the attachment to. */
    container?: { id: string; type: string };
}

export interface AuditRecord {
    author: { type: "user"; displayName: string; operations?: Array<OperationCheckResult>; username?: GenericUserName; userKey?: GenericUserKey; accountId?: GenericAccountId; accountType?: string; externalCollaborator?: boolean; isExternalCollaborator?: boolean; isGuest?: boolean; publicName?: string };
    remoteAddress: string;
    /** The creation date-time of the audit record, as a timestamp. */
    creationDate: number;
    summary: string;
    description: string;
    category: string;
    sysAdmin: boolean;
    superAdmin?: boolean;
    affectedObject: AffectedObject;
    changedValues: Array<ChangedValue>;
    associatedObjects: Array<AffectedObject>;
}

export interface AuditRecordArray {
    results: Array<AuditRecord>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

export interface AuditRecordCreate {
    /**
     * The user that actioned the event. If `author` is not specified, then all
     * `author` properties will be set to null/empty, except for `type` which
     * will be set to 'user'.
     */
    author?: { type: "user"; displayName?: string; operations?: Array<OperationCheckResult>; username?: GenericUserName; userKey?: GenericUserKey };
    /** The IP address of the computer where the event was initiated from. */
    remoteAddress: string;
    /**
     * The creation date-time of the audit record, as a timestamp. This is converted
     * to a date-time display in the Confluence UI. If the `creationDate` is not
     * specified, then it will be set to the timestamp for the current date-time.
     */
    creationDate?: number;
    /**
     * The summary of the event, which is displayed in the 'Change' column on
     * the audit log in the Confluence UI.
     */
    summary?: string;
    /**
     * A long description of the event, which is displayed in the 'Description'
     * field on the audit log in the Confluence UI.
     */
    description?: string;
    /**
     * The category of the event, which is displayed in the 'Event type' column
     * on the audit log in the Confluence UI.
     */
    category?: string;
    /** Indicates whether the event was actioned by a system administrator. */
    sysAdmin?: boolean;
    affectedObject?: AffectedObject;
    /** The values that were changed in the event. */
    changedValues?: Array<ChangedValue>;
    /**
     * Objects that were associated with the event. For example, if the event
     * was a space permission change then the associated object would be the
     * space.
     */
    associatedObjects?: Array<AffectedObject>;
}

export interface AvailableContentStates {
    /**
     * Space suggested content states that can be used in the space.
     * This list can be empty if there are no space content states defined in the space or if space content states are disabled in the space.
     * All spaces start with 4 default space content states, and this can be modified in the UI under space settings.
     */
    spaceContentStates: Array<ContentState>;
    /**
     * Custom content states that can be used by the user on the content of this call.
     * This list can be empty if there are no custom content states defined by the user or if custom content states are disabled in the space of the content.
     * This will at most have 3 of the most recently published content states. 
     * Only the calling user has access to place these states on content, but all users can see these states once they are placed.
     */
    customContentStates: Array<ContentState>;
}

export interface BlueprintTemplate {
    templateId: string;
    originalTemplate: { pluginKey: string; moduleKey: string };
    referencingBlueprint: string;
    name: string;
    description: string;
    space?: Record<string, unknown>;
    labels: Array<Label>;
    templateType: string;
    editorVersion?: string;
    body?: ContentTemplateBody;
    _expandable?: { body?: string };
    _links: GenericLinks;
}

export interface BlueprintTemplateArray {
    results: Array<BlueprintTemplate>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

export interface ButtonLookAndFeel {
    backgroundColor: string;
    color: string;
}

export interface Breadcrumb {
    label: string;
    url: string;
    separator: string;
}

export interface ChangedValue {
    name: string;
    oldValue: string;
    hiddenOldValue?: string;
    newValue: string;
    hiddenNewValue?: string;
}

/**
 * A [Connect module](https://developer.atlassian.com/cloud/confluence/modules/admin-page/) in the same format as in the
 * [app descriptor](https://developer.atlassian.com/cloud/confluence/app-descriptor/).
 */
export interface ConnectModule {
}

export interface ConnectModules {
    /**
     * A list of app modules in the same format as the `modules` property in the
     * [app descriptor](https://developer.atlassian.com/cloud/confluence/app-descriptor/).
     */
    modules: Array<ConnectModule>;
}

/**
 * Container for content. This can be either a space (containing a page or blogpost)
 * or a page/blog post (containing an attachment or comment)
 */
export type Container = Record<string, unknown>;

export interface ContainerLookAndFeel {
    background: string;
    backgroundAttachment?: string;
    backgroundBlendMode?: string;
    backgroundClip?: string;
    backgroundColor: string;
    backgroundImage: string;
    backgroundOrigin?: string;
    backgroundPosition?: string;
    backgroundRepeat?: string;
    backgroundSize: string;
    padding: string;
    borderRadius: string;
}

export interface ContainerSummary {
    title: string;
    displayUrl: string;
}

export type AttachmentPropertiesUpdateBody = Record<string, unknown>;
/** Base object for all content types. */
export type Content = Record<string, unknown>;

export interface ContentArray {
    results: Array<Content>;
    start?: number;
    limit?: number;
    size: number;
    _links: GenericLinks;
}

/** Representation of a blogpost (content) */
export type ContentBlogpost = Content & { metadata: ContentMetadata; _links: GenericLinks };
export type ContentBlueprintDraft = Record<string, unknown>;

export interface AsyncContentBody {
    value?: string;
    representation?: "view" | "export_view" | "styled_view" | "storage" | "editor" | "editor2" | "anonymous_export_view" | "wiki" | "atlas_doc_format";
    renderTaskId?: string;
    error?: string;
    /** Rerunning is reserved for when the job is working, but there is a previous run's value in the cache. You may choose to continue polling, or use the cached value. */
    status?: "WORKING" | "QUEUED" | "FAILED" | "COMPLETED" | "RERUNNING";
    embeddedContent?: Array<EmbeddedContent>;
    webresource?: WebResourceDependencies;
    mediaToken?: { collectionIds?: Array<string>; contentId?: string; expiryDateTime?: string; fileIds?: Array<string>; token?: string };
    _expandable?: { content?: string; embeddedContent?: string; webresource?: string; mediaToken?: string };
    _links?: GenericLinks;
}

export type AsyncContentBodyArray = Array<AsyncContentBody>;

export interface ContentBody {
    value: string;
    representation: "view" | "export_view" | "styled_view" | "storage" | "editor" | "editor2" | "anonymous_export_view" | "wiki" | "atlas_doc_format" | "raw";
    embeddedContent?: Array<EmbeddedContent>;
    webresource?: WebResourceDependencies;
    mediaToken?: { collectionIds?: Array<string>; contentId?: string; expiryDateTime?: string; fileIds?: Array<string>; token?: string };
    _expandable?: { content?: string; embeddedContent?: string; webresource?: string; mediaToken?: string };
    _links?: GenericLinks;
}

/** This object is used when creating or updating content. */
export type ContentBodyCreate = Record<string, unknown>;
export type ContentChildren = Record<string, unknown>;
/** This object is used when creating or updating content. */
export type ContentBodyCreateStorage = Record<string, unknown>;
/**
 * Shows whether a piece of content has attachments, comments, or child pages/whiteboards.
 * Note, this doesn't actually contain the child objects.
 */
export type ContentChildType = Record<string, unknown>;
export type ContentCreate = Record<string, unknown>;

export interface ContentHistory {
    latest: boolean;
    createdBy?: User;
    ownedBy?: User;
    lastOwnedBy?: User;
    createdDate?: string;
    lastUpdated?: Version;
    previousVersion?: Version;
    contributors?: { publishers?: UsersUserKeys };
    nextVersion?: Version;
    _expandable?: { lastUpdated?: string; previousVersion?: string; contributors?: string; nextVersion?: string; ownedBy?: string; lastOwnedBy?: string };
    _links?: GenericLinks;
}

export type ContentId = string;

export interface ContentLookAndFeel {
    screen?: ScreenLookAndFeel;
    container?: ContainerLookAndFeel;
    header?: ContainerLookAndFeel;
    body?: ContainerLookAndFeel;
}

/** Metadata object for page, blogpost, comment content */
export type ContentMetadata = Record<string, unknown>;
export type ContentProperty = Record<string, unknown>;

export interface ContentPropertyArray {
    results: Array<ContentProperty>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

export type ContentPropertyCreate = Record<string, unknown>;
export type ContentPropertyCreateNoKey = Record<string, unknown>;
export type ContentPropertyUpdate = Record<string, unknown>;

export interface ContentRestriction {
    operation: "administer" | "copy" | "create" | "delete" | "export" | "move" | "purge" | "purge_version" | "read" | "restore" | "update" | "use";
    restrictions?: { user?: UserArray; group?: GroupArray; _expandable?: { user?: string; group?: string } };
    content?: Content;
    _expandable: { restrictions?: string; content?: string };
    _links: GenericLinks;
}

export interface ContentRestrictionArray {
    results: Array<ContentRestriction>;
    start: number;
    limit: number;
    size: number;
    /**
     * This property is used by the UI to figure out whether a set of restrictions
     * has changed.
     */
    restrictionsHash: string;
    _links: GenericLinks;
}

export interface ContentRestrictionUpdate {
    /** The restriction operation applied to content. */
    operation: "administer" | "copy" | "create" | "delete" | "export" | "move" | "purge" | "purge_version" | "read" | "restore" | "update" | "use";
    /**
     * The users/groups that the restrictions will be applied to. At least one of
     * `user` or `group` must be specified for this object.
     */
    restrictions: { group?: Array<{ type: "group"; id?: string }>; user?: Array<User> | UserArray };
    content?: Content;
}

export type ContentRestrictionAddOrUpdateArray = { results: Array<ContentRestrictionUpdate>; start?: number; limit?: number; size?: number; restrictionsHash?: string; _links?: GenericLinks } | Array<ContentRestrictionUpdate>;

export interface AddContentRestriction {
    /** The restriction operation applied to content. */
    operation: "read" | "update";
    /**
     * The users/groups that the restrictions will be applied to. At least one of
     * `user` or `group` must be specified for this object.
     */
    restrictions: { user?: Array<{ type: "known" | "unknown" | "anonymous" | "user"; username?: GenericUserName; userKey?: GenericUserKey; accountId: GenericAccountId }>; group?: Array<{ type: "group"; name: string }> };
}

export type AddContentRestrictionUpdateArray = Array<AddContentRestriction>;

export interface ContentPageResponse {
    results: Array<Content>;
    start: number;
    limit: number;
    size: number;
}

export interface ContentState {
    /** identifier of content state. If 0, 1, or 2, this is a default space state */
    id: number;
    /** name of content state. */
    name: string;
    /** hex string representing color of state */
    color: string;
}

export interface ContentStateRestInput {
    /** Name of content state. Maximum 20 characters. */
    name?: string;
    /**
     * Color of state. Must be in 6 digit hex form (#FFFFFF). The default colors offered in the UI are:
     *  #ff7452 (red),
     *  #2684ff (blue),
     *  #ffc400 (yellow),
     *  #57d9a3 (green), and
     *  #8777d9 (purple)
     */
    color?: string;
    /** id of state. This can be 0,1, or 2 if you wish to specify a default space state. */
    id?: number;
}

export interface ContentStateResponse {
    /** Null or content state */
    contentState?: ContentState;
    /** Timestamp of last publish event where content state changed */
    lastUpdated?: string;
}

export interface ContentStateSettings {
    /** Whether users can place any content states on content */
    contentStatesAllowed: boolean;
    /** Whether users can place their custom states on content */
    customContentStatesAllowed: boolean;
    /** Whether users can place space suggested states on content */
    spaceContentStatesAllowed: boolean;
    /** space suggested content states that users can choose from */
    spaceContentStates?: Array<ContentState>;
}

export interface ContentTemplate {
    templateId: string;
    originalTemplate?: { pluginKey?: string; moduleKey?: string };
    referencingBlueprint?: string;
    name: string;
    description: string;
    space?: Record<string, unknown>;
    labels: Array<Label>;
    templateType: string;
    editorVersion?: string;
    body?: ContentTemplateBody;
    _expandable?: { body?: string };
    _links: GenericLinks;
}

export interface ContentTemplateArray {
    results: Array<ContentTemplate>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

/** This object is used to create content templates. */
export type ContentTemplateCreate = Record<string, unknown>;

/**
 * The body of the new content. Does not apply to attachments.
 * Only one body format should be specified as the property for
 * this object, e.g. `storage`.
 *
 * Note, `editor2` format is used by Atlassian only. `anonymous_export_view` is
 * the same as `export_view` format but only content viewable by an anonymous
 * user is included.
 */
export interface ContentTemplateBody {
    view?: ContentBody;
    export_view?: ContentBody;
    styled_view?: ContentBody;
    storage?: ContentBody;
    editor?: ContentBody;
    editor2?: ContentBody;
    wiki?: ContentBody;
    atlas_doc_format?: ContentBody;
    anonymous_export_view?: ContentBody;
}

/**
 * The body of the new content. Does not apply to attachments.
 * Only one body format should be specified as the property for
 * this object, e.g. `storage`.
 *
 * Note, `editor2` format is used by Atlassian only. `anonymous_export_view` is
 * the same as `export_view` format but only content viewable by an anonymous
 * user is included.
 */
export interface ContentTemplateBodyCreate {
    view?: ContentBodyCreate;
    export_view?: ContentBodyCreate;
    styled_view?: ContentBodyCreate;
    storage?: ContentBodyCreate;
    editor?: ContentBodyCreate;
    editor2?: ContentBodyCreate;
    wiki?: ContentBodyCreate;
    atlas_doc_format?: ContentBodyCreate;
    anonymous_export_view?: ContentBodyCreate;
}

/** This object is used to update content templates. */
export type ContentTemplateUpdate = Record<string, unknown>;
export type ContentUpdate = Record<string, unknown>;

export interface ContentBodyConversionInput {
    /** The name of the target format for the content body conversion. */
    to: string;
    /**
     * Controls whether conversion results are cached and reused for identical requests.
     *
     * - `false`: Each request creates a new conversion task, even if an identical request was made previously.
     * - `true`: Enables caching behavior for identical requests from the same user.
     *   - If no cached result exists, a new conversion task is created
     *   - If a cached result exists, the existing task is marked as RERUNNING and will complete with status COMPLETED
     *   - Returns the same task ID for identical requests, allowing you to retrieve the cached result
     */
    allowCache?: boolean;
    /** The space key used for resolving embedded content (page includes, files, and links) in the content body. For example, if the source content contains the link `<ac:link><ri:page ri:content-title="Example page" /><ac:link>` and the `spaceKeyContext=TEST` parameter is provided, then the link will be converted into a link to the "Example page" page in the "TEST" space. */
    spaceKeyContext?: string;
    /** The content ID used to find the space for resolving embedded content (page includes, files, and links) in the content body. For example, if the source content contains the link `<ac:link><ri:page ri:content-title="Example page" /><ac:link>` and the `contentIdContext=123` parameter is provided, then the link will be converted into a link to the "Example page" page in the same space that has the content with ID=123. Note that `spaceKeyContext` will be ignored if this parameter is provided. */
    contentIdContext?: string;
    /** Mode used for rendering embedded content, such as attachments. - `current` renders the embedded content using the latest version. - `version-at-save` renders the embedded content using the version at the time of save. */
    embeddedContentRender?: "current" | "version-at-save";
    /**
     * A multi-value, comma-separated parameter indicating which properties of the content to expand and populate. Expands are dependent
     * on the `to` conversion format and may be irrelevant for certain conversions (e.g. `macroRenderedOutput` is redundant when
     * converting to `view` format). 
     *
     * If rendering to `view` format, and the body content being converted includes arbitrary nested content (such as macros); then it is 
     * necessary to include webresource expands in the request. Webresources for content body are the batched JS and CSS dependencies for
     * any nested dynamic content (i.e. macros).
     *
     * - `embeddedContent` returns metadata for nested content (e.g. page included using page include macro)
     * - `mediaToken` returns JWT token for retrieving attachment data from Media API
     * - `macroRenderedOutput` additionally converts body to view format
     * - `webresource.superbatch.uris.js` returns all common JS dependencies as static URLs
     * - `webresource.superbatch.uris.css` returns all common CSS dependencies as static URLs
     * - `webresource.superbatch.uris.all` returns all common dependencies as static URLs
     * - `webresource.superbatch.tags.all` returns all common JS dependencies as html `<script>` tags
     * - `webresource.superbatch.tags.css` returns all common CSS dependencies as html `<style>` tags
     * - `webresource.superbatch.tags.js` returns all common dependencies as html `<script>` and `<style>` tags
     * - `webresource.uris.js` returns JS dependencies specific to conversion
     * - `webresource.uris.css` returns CSS dependencies specific to conversion
     * - `webresource.uris.all` returns all dependencies specific to conversion     
     * - `webresource.tags.all` returns common JS dependencies as html `<script>` tags
     * - `webresource.tags.css` returns common CSS dependencies as html `<style>` tags
     * - `webresource.tags.js` returns common dependencies as html `<script>` and `<style>` tags
     */
    expand?: Array<string>;
    body: ContentBodyCreate;
}

export interface BulkContentBodyConversionInput {
    conversionInputs?: Array<ContentBodyConversionInput>;
}

export interface CopyPageHierarchyRequest {
    /** If set to `true`, attachments are copied to the destination page. */
    copyAttachments?: boolean;
    /** If set to `true`, page permissions are copied to the destination page. */
    copyPermissions?: boolean;
    /** If set to `true`, content properties are copied to the destination page. */
    copyProperties?: boolean;
    /** If set to `true`, labels are copied to the destination page. */
    copyLabels?: boolean;
    /** If set to `true`, custom contents are copied to the destination page. */
    copyCustomContents?: boolean;
    /** If set to `true`, descendants are copied to the destination page. */
    copyDescendants?: boolean;
    destinationPageId: ContentId;
    titleOptions?: CopyPageHierarchyTitleOptions;
}

/** Required for copying page in the same space. */
export interface CopyPageHierarchyTitleOptions {
    prefix?: string;
    replace?: string;
    search?: string;
}

export interface CopyPageRequest {
    /** If set to `true`, attachments are copied to the destination page. */
    copyAttachments?: boolean;
    /** If set to `true`, page permissions are copied to the destination page. */
    copyPermissions?: boolean;
    /** If set to `true`, content properties are copied to the destination page. */
    copyProperties?: boolean;
    /** If set to `true`, labels are copied to the destination page. */
    copyLabels?: boolean;
    /** If set to `true`, custom contents are copied to the destination page. */
    copyCustomContents?: boolean;
    destination: CopyPageRequestDestination;
    /** If defined, this will replace the title of the destination page. */
    pageTitle?: string;
    /** If defined, this will replace the body of the destination page. */
    body?: { storage?: ContentBodyCreate; editor2?: ContentBodyCreate };
}

/**
 * Defines where the page will be copied to, and can be one of the following types.
 *
 *   - `parent_page`: page will be copied as a child of the specified parent page
 *   - `parent_content`: page will be copied as a child of the specified parent content
 *   - `space`: page will be copied to the specified space as a root page on the space
 *   - `existing_page`: page will be copied and replace the specified page
 */
export interface CopyPageRequestDestination {
    type: "space" | "existing_page" | "parent_page" | "parent_content";
    /** The space key for `space` type, and content id for `parent_page`, `parent_content`, and `existing_page` */
    value: string;
}

/** The converted CQL queries. */
export interface CQLPersonalDataConvertedQueries {
    /**
     * The list of converted CQL query strings with account IDs in
     * place of user identifiers.
     */
    queryStrings: Array<string>;
}

/** The CQL queries to be converted. */
export interface CQLPersonalDataMigrationRequest {
    /** A list of queries with user identifiers. Maximum of 100 queries. */
    queryStrings: Array<string>;
}

export interface DynamicModulesErrorMessage {
    /** The error message. */
    message: string;
}

export type Embeddable = Record<string, unknown>;
export type EmbeddedContent = Record<string, unknown>;
/**
 * The account ID of the user, which uniquely identifies the user across all Atlassian products.
 * For example, `384093:32b4d9w0-f6a5-3535-11a3-9c8c88d10192`.
 */
export type GenericAccountId = string;
export type GenericLinks = Record<string, Record<string, unknown> | string>;
/**
 * This property is no longer available and will be removed from the documentation soon.
 * Use `accountId` instead.
 * See the [deprecation notice](/cloud/confluence/deprecation-notice-user-privacy-api-migration-guide/) for details.
 */
export type GenericUserName = string;
/**
 * This property is no longer available and will be removed from the documentation soon.
 * Use `accountId` instead.
 * See the [deprecation notice](/cloud/confluence/deprecation-notice-user-privacy-api-migration-guide/) for details.
 */
export type GenericUserKey = string;

export interface GlobalSpaceIdentifier {
    spaceIdentifier: string;
}

export interface Group {
    type: "group";
    name: string;
    id: string;
    /**
     * This property represents how this collection of users is used:
     *   - `USERBASE_GROUP`: This value indicates that the collection of users is used as a group.
     *   - `TEAM_COLLABORATION`: This value indicates that the collection of users is used as a team.
     */
    usageType?: "USERBASE_GROUP" | "TEAM_COLLABORATION";
    /**
     * This property represents how this collection of users is managed:
     *   - `ADMINS`: This value indicates that the collection of users is managed by org, site or product admins.
     *   - `EXTERNAL`: This value indicates that the collection of users is managed externally (through SCIM, HRIS, etc.).
     *   - `TEAM_MEMBERS`: This value indicates that the collection of users is managed by its members.
     *   - `OPEN`: This value indicates that the collection of users is not actively managed by any users.
     */
    managedBy?: "ADMINS" | "EXTERNAL" | "TEAM_MEMBERS" | "OPEN";
    _links?: GenericLinks;
}

export type GroupCreate = Record<string, unknown>;

export interface GroupArray {
    results: Array<Group>;
    start: number;
    limit: number;
    size: number;
}

/** Same as GroupArray but with `_links` property. */
export interface GroupArrayWithLinks {
    results: Array<Group>;
    start: number;
    limit: number;
    size: number;
    /**
     * This property will return total count of the objects before pagination is applied.
     * This value is returned if `shouldReturnTotalSize` is set to `true`.
     */
    totalSize?: number;
    _links: GenericLinks;
}

export interface GroupName {
    name: string;
}

export interface HeaderLookAndFeel {
    backgroundColor: string;
    button: ButtonLookAndFeel;
    primaryNavigation: NavigationLookAndFeel;
    secondaryNavigation: NavigationLookAndFeel;
    search: SearchFieldLookAndFeel;
}

export interface HorizontalHeaderLookAndFeel {
    backgroundColor: string;
    button?: ButtonLookAndFeel;
    primaryNavigation: TopNavigationLookAndFeel;
    secondaryNavigation?: NavigationLookAndFeel;
    search?: SearchFieldLookAndFeel;
}

/** This object represents an icon. If used as a profilePicture, this may be returned as null, depending on the user's privacy setting. */
export interface Icon {
    path: string;
    width: number;
    height: number;
    isDefault: boolean;
}

export interface Label {
    prefix: string;
    name: string;
    id: string;
    label: string;
}

export interface LabelArray {
    results: Array<Label>;
    start?: number;
    limit?: number;
    size: number;
    _links?: GenericLinks;
}

export interface LabeledContent {
    contentType: LabeledContentType;
    contentId: number;
    /** Title of the content. */
    title: string;
}

export type LabeledContentType = "page" | "blogpost" | "attachment" | "page_template";

export interface LabeledContentPageResponse {
    results: Array<LabeledContent>;
    start?: number;
    limit?: number;
    size: number;
}

export interface LabelDetails {
    label: Label;
    associatedContents?: LabeledContentPageResponse;
}

export type LabelCreate = Record<string, unknown>;
export type LabelCreateArray = Array<LabelCreate>;

export interface LongTask {
    /** the ARI for the long task, based on its ID */
    ari?: string;
    /** a unique identifier for the long task */
    id: string;
    links: Record<string, unknown>;
}

export interface LookAndFeel {
    headings: { color: string };
    links: { color: string };
    menus: MenusLookAndFeel;
    header: HeaderLookAndFeel;
    horizontalHeader?: HorizontalHeaderLookAndFeel;
    content: ContentLookAndFeel;
    bordersAndDividers: { color: string };
    spaceReference?: Record<string, unknown>;
}

/** Look and feel settings returned after an update. */
export type LookAndFeelWithLinks = LookAndFeel & { _links?: GenericLinks };

/** Look and feel selection */
export interface LookAndFeelSelection {
    /**
     * The key of the space for which the look and feel settings will be
     * set.
     */
    spaceKey: string;
    lookAndFeelType: "global" | "custom" | "theme";
}

export interface LookAndFeelSettings {
    selected: "global" | "custom";
    global: LookAndFeel;
    theme?: LookAndFeel;
    custom: LookAndFeel;
}

/**
 * Current status of a long running task
 *
 * Status keys:
 *
 * - `ERROR_UNKNOWN` - Generic error
 * - `ERROR_LOCK_FAILED` - Could not get the lock on destination space
 * - `ERROR_RELINK` - Error when relink pages/attachments
 * - `ERROR_COPY_PAGE` - Error while copying 1 page
 * - `WARN_RENAME_PAGE` - Warning page is rename during copy
 * - `WARN_IGNORE_COPY_PERMISSION` - Warning could not copy permission
 * - `WARN_IGNORE_COPY_ATTACHMENT` - Warning could not copy attachment
 * - `WARN_IGNORE_DELETE_PAGE` - Warning ignoring delete of a non agreed on page
 * - `STATUS_COPIED_PAGES` - Message total pages are copied
 * - `STATUS_COPYING_PAGES` - Message copy pages
 * - `STATUS_RELINK_PAGES` - Message relink pages/attachments
 * - `STATUS_DELETING_PAGES` - Message delete pages
 * - `STATUS_DELETED_PAGES` - Message total pages are deleted
 * - `STATUS_MOVING_PAGES` - Message move pages
 * - `WARN_IGNORE_VIEW_RESTRICTED` - Permission changed - view restricted
 * - `WARN_IGNORE_EDIT_RESTRICTED` - Permission changed - edit restricted
 * - `INITIALIZING_TASK` - Message when initializing task
 * - `UNKNOWN_STATUS` - Message when status is unknown
 */
export interface LongTaskStatus {
    /** the ARI for the long task, based on its ID */
    ari?: string;
    id: string;
    name: { key: string; args: Array<Record<string, unknown>> };
    elapsedTime: number;
    percentageComplete: number;
    successful: boolean;
    finished: boolean;
    messages: Array<Message>;
    status?: string;
    errors?: Array<Message>;
    additionalDetails?: { destinationId?: string; destinationUrl?: string; totalPageNeedToCopy?: number; additionalProperties?: string };
}

export interface LongTaskStatusArray {
    results: Array<LongTaskStatus>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

/**
 * Same as LongTaskStatus but with `_links` property.
 *
 * Status keys:
 *
 * - `ERROR_UNKNOWN` - Generic error
 * - `ERROR_LOCK_FAILED` - Could not get the lock on destination space
 * - `ERROR_RELINK` - Error when relink pages/attachments
 * - `ERROR_COPY_PAGE` - Error while copying 1 page
 * - `WARN_RENAME_PAGE` - Warning page is rename during copy
 * - `WARN_IGNORE_COPY_PERMISSION` - Warning could not copy permission
 * - `WARN_IGNORE_COPY_ATTACHMENT` - Warning could not copy attachment
 * - `WARN_IGNORE_DELETE_PAGE` - Warning ignoring delete of a non agreed on page
 * - `STATUS_COPIED_PAGES` - Message total pages are copied
 * - `STATUS_COPYING_PAGES` - Message copy pages
 * - `STATUS_RELINK_PAGES` - Message relink pages/attachments
 * - `STATUS_DELETING_PAGES` - Message delete pages
 * - `STATUS_DELETED_PAGES` - Message total pages are deleted
 * - `STATUS_MOVING_PAGES` - Message move pages
 * - `WARN_IGNORE_VIEW_RESTRICTED` - Permission changed - view restricted
 * - `WARN_IGNORE_EDIT_RESTRICTED` - Permission changed - edit restricted
 * - `INITIALIZING_TASK` - Message when initializing task
 * - `UNKNOWN_STATUS` - Message when status is unknown
 */
export interface LongTaskStatusWithLinks {
    /** the ARI for the long task, based on its ID */
    ari?: string;
    id: string;
    name: { key: string; args: Array<Record<string, unknown>> };
    elapsedTime: number;
    percentageComplete: number;
    successful: boolean;
    finished: boolean;
    messages: Array<Message>;
    _links: GenericLinks;
    status?: string;
    errors?: Array<Message>;
    additionalDetails?: { destinationId?: string; destinationUrl?: string; totalPageNeedToCopy?: number; additionalProperties?: string };
}

export interface MacroInstance {
    name?: string;
    body?: string;
    parameters?: Record<string, unknown>;
    _links?: GenericLinks;
}

export interface MenusLookAndFeel {
    hoverOrFocus: { backgroundColor: string };
    color: string;
}

export type Message = Record<string, unknown>;

export interface BulkUserLookup {
    type: "known" | "unknown" | "anonymous" | "user";
    username?: GenericUserName;
    userKey?: GenericUserKey;
    accountId: GenericAccountId;
    /** The account type of the user, may return empty string if unavailable. */
    accountType: string;
    /** The email address of the user. Depending on the user's privacy setting, this may return an empty string. */
    email: string;
    /** The public name or nickname of the user. Will always contain a value. */
    publicName: string;
    profilePicture: Icon;
    /** The displays name of the user. Depending on the user's privacy setting, this may be the same as publicName. */
    displayName: string;
    /** This displays user time zone. Depending on the user's privacy setting, this may return null. */
    timeZone?: string;
    /** This is deprecated. Use `isGuest` instead to find out whether the user is a guest user. */
    isExternalCollaborator?: boolean;
    /** Whether the user is a guest user */
    isGuest?: boolean;
    operations?: Array<OperationCheckResult>;
    details?: UserDetails;
    personalSpace?: Space;
    _expandable: { operations?: string; details?: string; personalSpace?: string };
    _links: GenericLinks;
}

export interface BulkUserLookupArray {
    results: Array<BulkUserLookup>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

export interface NavigationLookAndFeel {
    color: string;
    highlightColor?: string;
    hoverOrFocus: { backgroundColor: string; color: string };
}

export interface TopNavigationLookAndFeel {
    color?: string;
    highlightColor: string;
    hoverOrFocus?: { backgroundColor?: string; color?: string };
}

/** An operation and the target entity that it applies to, e.g. create page. */
export interface OperationCheckResult {
    /** The operation itself. */
    operation: "administer" | "archive" | "clear_permissions" | "copy" | "create" | "create_space" | "delete" | "export" | "move" | "purge" | "purge_version" | "read" | "restore" | "restrict_content" | "update" | "use";
    /** The space or content type that the operation applies to. Could be one of- - application - page - blogpost - comment - attachment - space */
    targetType: string;
}

/**
 * The value of the property. This can be empty or a complex object. 64KB Size Limit
 * For example,
 * ```
 * "value": {
 *   "example1": "value",
 *   "example2": true,
 *   "example3": 123,
 *   "example4": ["value1", "value2"],
 * }
 * ```
 */
export type PropertyValue = Array<string> | boolean | Record<string, unknown> | string;

export interface Relation {
    name: string;
    relationData?: RelationData;
    source?: Content | User | Space;
    target?: Content | User | Space;
    _expandable?: { relationData?: string; source?: string; target?: string };
    _links: GenericLinks;
}

export interface RelationArray {
    results: Array<Relation>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

export interface RelationData {
    createdBy?: User;
    createdDate?: string;
    friendlyCreatedDate?: string;
}

export interface RetentionPeriod {
    /** The number of units for the retention period. */
    number: number;
    /** The unit of time that the retention period is measured in. */
    units: "NANOS" | "MICROS" | "MILLIS" | "SECONDS" | "MINUTES" | "HOURS" | "HALF_DAYS" | "DAYS" | "WEEKS" | "MONTHS" | "YEARS" | "DECADES" | "CENTURIES" | "MILLENNIA" | "ERAS" | "FOREVER";
}

export interface ScreenLookAndFeel {
    background: string;
    backgroundAttachment?: string;
    backgroundBlendMode?: string;
    backgroundClip?: string;
    backgroundColor?: string;
    backgroundImage?: string;
    backgroundOrigin?: string;
    backgroundPosition?: string;
    backgroundRepeat?: string;
    backgroundSize?: string;
    layer?: { width?: string; height?: string };
    gutterTop?: string;
    gutterRight?: string;
    gutterBottom?: string;
    gutterLeft?: string;
}

export interface SearchFieldLookAndFeel {
    backgroundColor: string;
    color: string;
}

export interface SearchPageResponseSearchResult {
    results: Array<SearchResult>;
    start: number;
    limit: number;
    size: number;
    totalSize: number;
    cqlQuery: string;
    searchDuration: number;
    archivedResultCount?: number;
    _links: GenericLinks;
}

export interface SearchResult {
    content?: Content;
    user?: User;
    space?: Space;
    title: string;
    excerpt: string;
    url: string;
    resultParentContainer?: ContainerSummary;
    resultGlobalContainer?: ContainerSummary;
    breadcrumbs: Array<Breadcrumb>;
    entityType: string;
    iconCssClass: string;
    lastModified: string;
    friendlyLastModified?: string;
    score?: number;
}

export interface Space {
    id?: number;
    key: string;
    alias?: string;
    name: string;
    icon?: Icon;
    description?: { plain?: SpaceDescription; view?: SpaceDescription; _expandable?: { view?: string; plain?: string } };
    homepage?: Content;
    type: string;
    metadata?: { labels?: LabelArray; _expandable?: Record<string, unknown> };
    operations?: Array<OperationCheckResult>;
    permissions?: Array<SpacePermission>;
    status: string;
    settings?: SpaceSettings;
    theme?: Theme;
    lookAndFeel?: LookAndFeel;
    history?: { createdDate: string; createdBy?: User };
    _expandable: { settings?: string; metadata?: string; operations?: string; lookAndFeel?: string; permissions?: string; icon?: string; description?: string; theme?: string; history?: string; homepage?: string; identifiers?: string };
    _links: GenericLinks;
}

export interface SpaceArray {
    results: Array<Space>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

/** This is the request object used when creating a new space. */
export type SpaceCreate = Record<string, unknown>;
/** The properties of a space that can be updated. */
export type SpaceUpdate = Record<string, unknown>;
export type SpaceDescription = Record<string, unknown>;

/**
 * The description of the new/updated space. Note, only the 'plain' representation
 * can be used for the description when creating or updating a space.
 */
export interface SpaceDescriptionCreate {
    plain: Record<string, unknown>;
}

/**
 * This object represents a permission for given space. Permissions consist of
 * at least one operation object with an accompanying subjects object.
 *
 * The following combinations of `operation` and `targetType` values are
 * valid for the `operation` object:
 *
 *   - 'create': 'page', 'blogpost', 'comment', 'attachment'
 *   - 'read': 'space'
 *   - 'delete': 'page', 'blogpost', 'comment', 'attachment'
 *   - 'export': 'space'
 *   - 'administer': 'space'
 */
export interface SpacePermission {
    id?: number;
    /** The users and/or groups that the permission applies to. */
    subjects?: { user?: { results: Array<User>; size: number; start?: number; limit?: number }; group?: { results: Array<Group>; size: number; start?: number; limit?: number }; _expandable?: { user?: string; group?: string } };
    operation: OperationCheckResult;
    /** Grant anonymous users permission to use the operation. */
    anonymousAccess: boolean;
    /**
     * Grants access to unlicensed users from JIRA Service Desk when used
     * with the 'read space' operation.
     */
    unlicensedAccess: boolean;
}

/**
 * This object represents a permission for given space. Permissions consist of
 * at least one operation object with an accompanying subjects object.
 *
 * The following combinations of `operation` and `targetType` values are
 * valid for the `operation` object:
 *
 *   - 'create': 'page', 'blogpost', 'comment', 'attachment'
 *   - 'read': 'space'
 *   - 'delete': 'page', 'blogpost', 'comment', 'attachment'
 *   - 'export': 'space'
 *   - 'administer': 'space'
 */
export type SpacePermissionCreate = Record<string, unknown>;

export interface SpaceProperty {
    id: string;
    key: string;
    value: Array<string> | boolean | Record<string, unknown> | string;
    version?: Version;
    space?: Space;
    _links?: GenericLinks;
    _expandable: { version?: string; space?: string };
}

export interface SpacePropertyArray {
    results: Array<SpaceProperty>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

export interface SpacePropertyCreate {
    /** The key of the new property. */
    key: string;
    value: PropertyValue;
    space?: Record<string, unknown>;
}

export interface SpacePropertyCreateNoKey {
    value: PropertyValue;
}

export interface SpacePropertyUpdate {
    key?: string;
    value: Array<string> | boolean | Record<string, unknown> | string;
    version: Version;
    space?: Record<string, unknown>;
}

export interface SpaceSettings {
    /**
     * Defines whether an override for the space home should be used. This is
     * used in conjunction with a space theme provided by an app. For
     * example, if this property is set to true, a theme can display a page
     * other than the space homepage when users visit the root URL for a
     * space. This property allows apps to provide content-only theming
     * without overriding the space home.
     */
    routeOverrideEnabled: boolean;
    editor?: { page: string; blogpost: string; default: string };
    spaceKey?: string;
    _links: GenericLinks;
}

export interface SpaceSettingsUpdate {
    /**
     * Defines whether an override for the space home should be used. This is
     * used in conjunction with a space theme provided by an app. For
     * example, if this property is set to true, a theme can display a page
     * other than the space homepage when users visit the root URL for a
     * space. This property allows apps to provide content-only theming
     * without overriding the space home.
     */
    routeOverrideEnabled?: boolean;
}

export interface SpaceWatch {
    type: string;
    watcher: WatchUser;
    spaceKey?: string;
    labelName?: string;
    prefix?: string;
}

export interface SpaceWatchArray {
    results: Array<SpaceWatch>;
    start: number;
    limit: number;
    size: number;
    _links?: GenericLinks;
}

export interface SuperBatchWebResources {
    uris?: { all?: Array<string> | string; css?: Array<string> | string; js?: Array<string> | string };
    tags?: { all?: string; css?: string; data?: string; js?: string };
    metatags?: string;
    _expandable?: Record<string, unknown>;
}

export interface SystemInfoEntity {
    cloudId: string;
    commitHash: string;
    baseUrl?: string;
    fallbackBaseUrl?: string;
    edition?: string;
    siteTitle?: string;
    defaultLocale?: string;
    defaultTimeZone?: string;
    microsPerimeter?: string;
}

export interface TaskStatusUpdate {
    status: "complete" | "incomplete";
}

export interface Task {
    globalId: number;
    id: number;
    contentId: number;
    status: string;
    title?: string;
    description?: string;
    body?: string;
    creator: string;
    assignee?: string;
    completeUser?: string;
    createDate: number;
    dueDate?: number;
    updateDate?: number;
    completeDate?: number;
    _links?: GenericLinks;
}

export interface TaskPageResponse {
    results: Array<Task>;
    start: number;
    limit: number;
    size: number;
}

export interface Theme {
    themeKey: string;
    name?: string;
    description?: string;
    icon?: Icon;
    _links?: GenericLinks;
}

/** Theme object without links. Used in ThemeArray. */
export interface ThemeNoLinks {
    themeKey: string;
    name?: string;
    description?: string;
    icon?: Icon;
}

export interface ThemeArray {
    results: Array<ThemeNoLinks>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

export interface ThemeUpdate {
    /** The key of the theme to be set as the space theme. */
    themeKey: string;
}

export type User = Record<string, unknown>;

export interface UserAnonymous {
    type: string;
    profilePicture: Icon;
    displayName: string;
    operations?: Array<OperationCheckResult>;
    _expandable?: { operations?: string };
    _links: GenericLinks;
}

export interface UserArray {
    results: Array<User>;
    start?: number;
    limit?: number;
    size?: number;
    /**
     * This property will return total count of the objects before pagination is applied.
     * This value is returned if `shouldReturnTotalSize` is set to `true`.
     */
    totalSize?: number;
    _links?: GenericLinks;
}

export interface UserDetails {
    business?: { position?: string; department?: string; location?: string };
    personal?: { phone?: string; im?: string; website?: string; email?: string };
}

export interface UserProperty {
    key: string;
    /** The value of the content property. */
    value: Record<string, unknown>;
    /** a unique identifier for the user property */
    id: string;
    /** datetime when the property was last modified such as `2022-02-01T12:00:00.111Z` */
    lastModifiedDate: string;
    /** datetime when the property was created such as `2022-01-01T12:00:00.111Z` */
    createdDate: string;
    _links?: GenericLinks;
}

export interface UserPropertyKeyArray {
    results: Array<{ key?: string }>;
    start?: number;
    limit?: number;
    size?: number;
    _links?: GenericLinks;
}

export interface UserPropertyCreate {
    /** The value of the user property. */
    value: Record<string, unknown>;
}

export interface UserPropertyUpdate {
    /** The value of the user property. */
    value: Record<string, unknown>;
}

export type UsersUserKeys = Record<string, unknown>;

export interface UserWatch {
    watching: boolean;
}

export type Version = Record<string, unknown>;

export interface VersionArray {
    results: Array<Version>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

export interface VersionRestore {
    /** Set to 'restore'. */
    operationKey: "restore";
    params: { versionNumber: number; message: string; restoreTitle?: boolean };
}

export interface Watch {
    type: string;
    watcher: WatchUser;
    contentId: number;
}

export interface WatchArray {
    results: Array<Watch>;
    start: number;
    limit: number;
    size: number;
    _links: GenericLinks;
}

/**
 * This essentially the same as the `User` object, but no `_links` property and
 * no `_expandable` property (therefore, different required fields).
 */
export interface WatchUser {
    type: string;
    username?: GenericUserName;
    userKey?: GenericUserKey;
    accountId: GenericAccountId;
    profilePicture: Icon;
    displayName: string;
    timeZone?: string;
    operations: Array<OperationCheckResult>;
    externalCollaborator: boolean;
    isGuest: boolean;
    isExternalCollaborator: boolean;
    details?: UserDetails;
    accountType: string;
    email: string;
    publicName: string;
    personalSpace: Record<string, unknown>;
}

export interface WebResourceDependencies {
    _expandable?: Record<string, unknown>;
    keys?: Array<string>;
    contexts?: Array<string>;
    uris?: { all?: Array<string> | string; css?: Array<string> | string; js?: Array<string> | string; _expandable?: Record<string, unknown> };
    tags?: { all?: string; css?: string; data?: string; js?: string; _expandable?: Record<string, unknown> };
    superbatch?: SuperBatchWebResources;
}

/** The user or group that the permission applies to. */
export interface PermissionSubject {
    type: "user" | "group";
    /**
     * for `type=user`, identifier should be user's accountId or `anonymous` for anonymous users
     *
     * for `type=group`, identifier should be the groupId.
     */
    identifier: string;
}

/** The user or group that the permission applies to. */
export interface PermissionSubjectWithGroupId {
    type: "user" | "group";
    /**
     * for `type=user`, identifier should be user's accountId or `anonymous` for anonymous users
     *
     * for `type=group`, identifier should be ID of the group
     */
    identifier: string;
}

/**
 * This object represents a single space permission. Permissions consist of
 * at least one operation object with an accompanying subjects object.
 *
 * The following combinations of `operation.key` and `operation.target` values are
 * valid for the `operation` object:
 * ``` bash
 * 'create': 'page', 'blogpost', 'comment', 'attachment'
 * 'read': 'space'
 * 'delete': 'page', 'blogpost', 'comment', 'attachment', 'space'
 * 'export': 'space'
 * 'administer': 'space'
 * 'archive': 'page'
 * 'restrict_content': 'space'
 * ```
 *
 * For example, to enable Delete Own permission, set the `operation` object to the following:
 * ```
 * "operation": {
 *     "key": "delete",
 *     "target": "space"
 * }
 * ```
 * To enable Add/Delete Restrictions permissions, set the `operation` object to the following:
 * ```
 * "operation": {
 *     "key": "restrict_content",
 *     "target": "space"
 * }
 * ```
 */
export interface SpacePermissionV2 {
    id: number;
    subject: PermissionSubject;
    operation: { key: "administer" | "archive" | "copy" | "create" | "delete" | "export" | "move" | "purge" | "purge_version" | "read" | "restore" | "restrict_content" | "update" | "use"; target: "page" | "blogpost" | "comment" | "attachment" | "space" };
    _links?: GenericLinks;
}

/**
 * This object represents the request for the single space permission. Permissions consist of
 * one operation object with an accompanying subjects object.
 *
 * The following combinations of `operation.key` and `operation.target` values are
 * valid for the `operation` object:
 * ``` bash
 * 'create': 'page', 'blogpost', 'comment', 'attachment'
 * 'read': 'space'
 * 'delete': 'page', 'blogpost', 'comment', 'attachment', 'space'
 * 'export': 'space'
 * 'administer': 'space'
 * 'archive': 'page'
 * 'restrict_content': 'space'
 * ```
 *
 * For example, to enable Delete Own permission, set the `operation` object to the following:
 * ```
 * "operation": {
 *     "key": "delete",
 *     "target": "space"
 * }
 * ```
 * To enable Add/Delete Restrictions permissions, set the `operation` object to the following:
 * ```
 * "operation": {
 *     "key": "restrict_content",
 *     "target": "space"
 * }
 * ```
 */
export type SpacePermissionRequest = Record<string, unknown>;

/**
 * This object represents a list of space permissions for custom content type for an individual user. Permissions consist of
 * a subjects object and a list with at least one operation object.
 */
export interface SpacePermissionCustomContent {
    subject: PermissionSubject;
    operations: Array<{ key: "read" | "create" | "delete"; target: string; access: boolean }>;
}

/** This object represents the request for the content permission check API. */
export interface ContentPermissionRequest {
    subject: PermissionSubjectWithGroupId;
    /** The content permission operation to check. */
    operation: "read" | "update" | "delete";
}

/**
 * This object represents the response for the content permission check API. If the user or group does not have
 * permissions, the following errors may be returned:
 *
 * - Group does not have permission to the space
 * - Group does not have permission to the content
 * - User is not allowed to use Confluence
 * - User does not have permission to the space
 * - User does not have permission to the content
 * - Anonymous users are not allowed to use Confluence
 * - Anonymous user does not have permission to the space
 * - Anonymous user does not have permission to the content
 */
export interface PermissionCheckResponse {
    hasPermission: boolean;
    errors?: Array<Message>;
    _links?: GenericLinks;
}

export interface ErrorResponse {
    errorMessages?: Array<string>;
    errors?: Record<string, string>;
    status?: number;
    message?: string;
}

export interface RateLimitError {
    message?: string;
    retryAfter?: number;
}
