/**
 * @forge-clients/generator CLI — Option 4 (Custom TypeScript AST Generator)
 * forge-clients-gen update-specs      Download and process Atlassian OpenAPI specs
 * forge-clients-gen generate          Generate TypeScript clients via IR + ts-morph
 */
import { Command } from 'commander';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync, mkdirSync } from 'fs';
import SwaggerParser from '@apidevtools/swagger-parser';
import type { OpenAPIV3 } from 'openapi-types';
import { runSpecPipeline } from './pipeline/run.js';
import { specToIR } from './ir/SpecToIR.js';
import { TypeEmitter } from './emitters/TypeEmitter.js';
import { SdkEmitter } from './emitters/SdkEmitter.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..', '..');

const TARGETS = [
  { id: 'jira-v3',       specPath: 'packages/specs/src/cleaned/jira-v3.json',       outDir: 'packages/jira/src/v3',                  title: 'Jira Cloud REST API v3' },
  { id: 'jira-v2',       specPath: 'packages/specs/src/cleaned/jira-v2.json',       outDir: 'packages/jira/src/v2',                  title: 'Jira Cloud REST API v2' },
  { id: 'jira-software', specPath: 'packages/specs/src/cleaned/jira-software.json', outDir: 'packages/jira/src/software',             title: 'Jira Software Cloud REST API' },
  { id: 'jira-sm',       specPath: 'packages/specs/src/cleaned/jira-sm.json',       outDir: 'packages/jira/src/service-management',   title: 'Jira Service Management Cloud REST API' },
  { id: 'confluence-v1', specPath: 'packages/specs/src/cleaned/confluence-v1.json', outDir: 'packages/confluence/src/v1',             title: 'Confluence Cloud REST API v1' },
];

const program = new Command();

program
  .name('forge-clients-gen')
  .description('Generator CLI for @forge-clients — Option 4 (Custom TypeScript AST Generator)')
  .version('0.1.0');

program
  .command('update-specs')
  .description('Download and process the latest Atlassian OpenAPI specs')
  .option('--force', 'Force re-download even if raw specs are cached')
  .option('--dry-run', 'Show what would change without writing cleaned specs')
  .option('--skip-download', 'Skip download step — use existing cached raw specs')
  .option('--only <specs>', 'Comma-separated spec IDs to process (e.g. jira-v3,confluence-v2)')
  .action(async (options: {
    force?: boolean;
    dryRun?: boolean;
    skipDownload?: boolean;
    only?: string;
  }) => {
    try {
      await runSpecPipeline({
        force: options.force,
        dryRun: options.dryRun,
        skipDownload: options.skipDownload,
        only: options.only ? options.only.split(',').map(s => s.trim()) : undefined,
      });
    } catch (err) {
      console.error('\n❌ Pipeline failed:', (err as Error).message);
      process.exit(1);
    }
  });

program
  .command('generate')
  .description('Generate TypeScript clients via IR + ts-morph AST emitters')
  .option('--only <specs>', 'Comma-separated spec IDs to generate (e.g. jira-v3,confluence-v1)')
  .action(async (options: { only?: string }) => {
    const typeEmitter = new TypeEmitter();
    const sdkEmitter = new SdkEmitter();
    const only = options.only ? options.only.split(',').map(s => s.trim()) : null;
    const targets = only ? TARGETS.filter(t => only.includes(t.id)) : TARGETS;

    console.log(`\n🔨 @forge-clients/generator (Option 4: Custom AST) — generating clients...`);
    console.log(`   Targets: ${targets.map(t => t.id).join(', ')}\n`);

    const totalStart = performance.now();
    const timings: Array<{ id: string; ms: number; ops: number; schemas: number }> = [];

    for (const target of targets) {
      const specPath = resolve(repoRoot, target.specPath);
      const outDir = resolve(repoRoot, target.outDir);
      console.log(`\n📐 Processing: ${target.title}`);

      // Use bundle (not dereference) to safely handle circular $refs in Atlassian specs.
      // dereference() inlines all $refs recursively — Jira's schemas contain circular
      // references which cause a stack overflow. bundle() preserves $refs as-is.
      const start = performance.now();
      const spec = await SwaggerParser.bundle(specPath) as OpenAPIV3.Document;
      const ir = specToIR(spec, target.title);
      console.log(`   Operations: ${ir.operations.length}, Types: ${ir.types.size}`);

      const banner = '// Generated by @forge-clients/generator — DO NOT EDIT\n' +
        '// Source: ' + target.title + '\n';
      mkdirSync(outDir, { recursive: true });

      writeFileSync(resolve(outDir, 'types.gen.ts'), typeEmitter.emit(ir, banner));
      console.log('   ✅ types.gen.ts');
      writeFileSync(resolve(outDir, 'sdk.gen.ts'), sdkEmitter.emit(ir, banner));
      console.log('   ✅ sdk.gen.ts');
      const indexContent = [
        `/**`,
        ` * ${target.title}`,
        ` *`,
        ` * Generated by @forge-clients/generator. DO NOT EDIT.`,
        ` * Run \`pnpm generate --only ${target.id}\` to regenerate.`,
        ` *`,
        ` * - types.gen.ts  TypeScript interfaces for all request/response schemas`,
        ` * - sdk.gen.ts    Named, tree-shakeable async functions for every endpoint`,
        ` */`,
        ``,
        `// All TypeScript types — zero runtime cost, erased at build time`,
        // Note: 'export type *' (TS 5.0+) is not supported by Forge's webpack/ts-loader bundler.
        // Since types.gen.ts contains only interfaces (erased at runtime), plain 'export *' is safe.
        `export * from './types.gen.js';`,
        ``,
        `// All named SDK functions — individually tree-shakeable`,
        `export * from './sdk.gen.js';`,
        ``,
      ].join('\n');
      writeFileSync(resolve(outDir, 'index.ts'), indexContent);
      console.log('   ✅ index.ts');

      const elapsed = Math.round(performance.now() - start);
      timings.push({ id: target.id, ms: elapsed, ops: ir.operations.length, schemas: ir.types.size });
      console.log('   ⏱  Completed in ' + (elapsed / 1000).toFixed(1) + 's');
    }

    const total = Math.round(performance.now() - totalStart);
    console.log('\n✅ Generation complete!');
    console.log('\n📊 Timing Summary:');
    const col = (s: string, w: number) => s.padEnd(w);
    const rcol = (s: string, w: number) => s.padStart(w);
    console.log('   ' + col('Spec', 20) + rcol('Ops', 6) + rcol('Types', 7) + rcol('Time', 9) + rcol('Rate', 10));
    console.log('   ' + '-'.repeat(55));
    for (const t of timings) {
      const rate = Math.round(t.ops / (t.ms / 1000));
      console.log('   ' + col(t.id, 20) + rcol(String(t.ops), 6) + rcol(String(t.schemas), 7) +
        rcol((t.ms / 1000).toFixed(1) + 's', 9) + rcol(rate + ' ops/s', 10));
    }
    console.log('   ' + '-'.repeat(55));
    const totalOps = timings.reduce((a, t) => a + t.ops, 0);
    const totalSchemas = timings.reduce((a, t) => a + t.schemas, 0);
    console.log('   ' + col('TOTAL', 20) + rcol(String(totalOps), 6) + rcol(String(totalSchemas), 7) +
      rcol((total / 1000).toFixed(1) + 's', 9));
  });

program.parse();
