#!/usr/bin/env node
/**
 * @forge-clients/generator CLI — Option 4 (Custom TypeScript AST Generator)
 * forge-clients-gen update-specs      Download and process Atlassian OpenAPI specs
 * forge-clients-gen generate          Generate TypeScript clients via IR + ts-morph
 */
import { Command } from 'commander';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync, mkdirSync } from 'fs';
import SwaggerParser from '@apidevtools/swagger-parser';
import type { OpenAPIV3 } from 'openapi-types';
import { runSpecPipeline } from './pipeline/run.js';
import { specToIR } from './ir/SpecToIR.js';
import { TypeEmitter } from './emitters/TypeEmitter.js';
import { SdkEmitter } from './emitters/SdkEmitter.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..', '..');

const TARGETS = [
  { specPath: 'packages/specs/src/cleaned/jira-v3.json',       outDir: 'packages/jira/src/v3',       title: 'Jira Cloud REST API v3' },
  { specPath: 'packages/specs/src/cleaned/jira-v2.json',       outDir: 'packages/jira/src/v2',       title: 'Jira Cloud REST API v2' },
  { specPath: 'packages/specs/src/cleaned/confluence-v2.json', outDir: 'packages/confluence/src/v2', title: 'Confluence Cloud REST API v2' },
  { specPath: 'packages/specs/src/cleaned/confluence-v1.json', outDir: 'packages/confluence/src/v1', title: 'Confluence Cloud REST API v1' },
];

const program = new Command();

program
  .name('forge-clients-gen')
  .description('Generator CLI for @forge-clients — Option 4 (Custom TypeScript AST Generator)')
  .version('0.1.0');

program
  .command('update-specs')
  .description('Download and process the latest Atlassian OpenAPI specs')
  .option('--force', 'Force re-download even if raw specs are cached')
  .option('--dry-run', 'Show what would change without writing cleaned specs')
  .option('--skip-download', 'Skip download step — use existing cached raw specs')
  .option('--only <specs>', 'Comma-separated spec IDs to process (e.g. jira-v3,confluence-v2)')
  .action(async (options: {
    force?: boolean;
    dryRun?: boolean;
    skipDownload?: boolean;
    only?: string;
  }) => {
    try {
      await runSpecPipeline({
        force: options.force,
        dryRun: options.dryRun,
        skipDownload: options.skipDownload,
        only: options.only ? options.only.split(',').map(s => s.trim()) : undefined,
      });
    } catch (err) {
      console.error('\n❌ Pipeline failed:', (err as Error).message);
      process.exit(1);
    }
  });

program
  .command('generate')
  .description('Generate TypeScript clients via IR + ts-morph AST emitters')
  .option('--spec <spec>', 'Which spec to generate (jira-v3, jira-v2, confluence-v2, confluence-v1, all)', 'all')
  .action(async (options: { spec: string }) => {
    const typeEmitter = new TypeEmitter();
    const sdkEmitter = new SdkEmitter();
    const targets = options.spec === 'all'
      ? TARGETS
      : TARGETS.filter(t => t.specPath.includes(options.spec));

    for (const target of targets) {
      const specPath = resolve(repoRoot, target.specPath);
      const outDir = resolve(repoRoot, target.outDir);
      console.log(`\n📐 Processing: ${target.title}`);
      const spec = await SwaggerParser.dereference(specPath) as OpenAPIV3.Document;
      const ir = specToIR(spec, target.title);
      console.log(`   Operations: ${ir.operations.length}, Types: ${ir.types.size}`);
      const banner = `// Generated by @forge-clients/generator — DO NOT EDIT\n// Source: ${target.title}\n`;
      mkdirSync(outDir, { recursive: true });
      writeFileSync(resolve(outDir, 'types.gen.ts'), typeEmitter.emit(ir, banner));
      console.log(`   ✅ types.gen.ts`);
      writeFileSync(resolve(outDir, 'sdk.gen.ts'), sdkEmitter.emit(ir, banner));
      console.log(`   ✅ sdk.gen.ts`);
    }
    console.log('\n✅ Generation complete!');
  });

program.parse();
