#!/usr/bin/env node
/**
 * @forge-clients/generator CLI — Option 4 (Custom TypeScript AST Generator)
 * forge-clients-gen generate          Generate types + SDK from cleaned specs via IR + ts-morph
 * forge-clients-gen update-specs      Download and patch the latest Atlassian specs
 */
import { Command } from 'commander';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync, mkdirSync } from 'fs';
import SwaggerParser from '@apidevtools/swagger-parser';
import type { OpenAPIV3 } from 'openapi-types';
import { specToIR } from './ir/SpecToIR.js';
import { TypeEmitter } from './emitters/TypeEmitter.js';
import { SdkEmitter } from './emitters/SdkEmitter.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..', '..');

const TARGETS = [
  { specPath: 'packages/specs/src/cleaned/jira-v3.json',        outDir: 'packages/jira/src/v3',         title: 'Jira Cloud REST API v3' },
  { specPath: 'packages/specs/src/cleaned/jira-v2.json',        outDir: 'packages/jira/src/v2',         title: 'Jira Cloud REST API v2' },
  { specPath: 'packages/specs/src/cleaned/confluence-v2.json',  outDir: 'packages/confluence/src/v2',   title: 'Confluence Cloud REST API v2' },
  { specPath: 'packages/specs/src/cleaned/confluence-v1.json',  outDir: 'packages/confluence/src/v1',   title: 'Confluence Cloud REST API v1' },
];

const program = new Command();

program
  .name('forge-clients-gen')
  .description('Generator CLI for @forge-clients — Option 4 (Custom TypeScript AST Generator)')
  .version('0.1.0');

program
  .command('generate')
  .description('Generate TypeScript types and SDK functions from cleaned specs via IR + ts-morph')
  .option('--spec <spec>', 'Which spec to generate (jira-v3, jira-v2, confluence-v2, confluence-v1, all)', 'all')
  .action(async (options: { spec: string }) => {
    const typeEmitter = new TypeEmitter();
    const sdkEmitter = new SdkEmitter();

    const targets = options.spec === 'all'
      ? TARGETS
      : TARGETS.filter(t => t.specPath.includes(options.spec));

    for (const target of targets) {
      const specPath = resolve(repoRoot, target.specPath);
      const outDir = resolve(repoRoot, target.outDir);

      console.log(`\n📐 Processing: ${target.title}`);

      const spec = await SwaggerParser.dereference(specPath) as OpenAPIV3.Document;
      const ir = specToIR(spec, target.title);

      console.log(`   Operations: ${ir.operations.length}, Types: ${ir.types.size}`);

      const banner = `// Generated by @forge-clients/generator — DO NOT EDIT\n// Source: ${target.title}\n`;

      mkdirSync(outDir, { recursive: true });

      const typesCode = typeEmitter.emit(ir, banner);
      writeFileSync(resolve(outDir, 'types.gen.ts'), typesCode);
      console.log(`   ✅ types.gen.ts`);

      const sdkCode = sdkEmitter.emit(ir, banner);
      writeFileSync(resolve(outDir, 'sdk.gen.ts'), sdkCode);
      console.log(`   ✅ sdk.gen.ts`);
    }

    console.log('\n✅ Generation complete!');
  });

program
  .command('update-specs')
  .description('Download the latest Atlassian OpenAPI specs and apply post-processing pipeline')
  .action(() => {
    console.log('update-specs — spec pipeline implementation pending');
    process.exit(0);
  });

program.parse();
