import { ForgeApiError } from "@forge-clients/core";
import type { ForgeAdapter, AuthContext } from "@forge-clients/core";
import type * as Types from "./types.gen.js";

// Generated by @forge-clients/generator — DO NOT EDIT
// Source: Jira Service Management Cloud REST API
/* eslint-disable */
export type * from './types.gen.js';

export interface GetAssetsWorkspacesParams {
    start?: number;
    limit?: number;
}

/**
 * Get assets workspaces
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getAssetsWorkspaces(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetAssetsWorkspacesParams): Promise<Types.PagedDTOAssetsWorkspaceDTO> {
    const path = '/rest/servicedeskapi/assets/workspace';
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOAssetsWorkspaceDTO>;
}

export interface CreateCustomerParams {
    strictConflictStatusCode?: boolean;
    body?: CustomerCreateDTO;
}

/**
 * Create customer
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function createCustomer(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: CreateCustomerParams): Promise<Types.UserDTO> {
    const path = '/rest/servicedeskapi/customer';
    const queryParams = {
      strictConflictStatusCode: params.strictConflictStatusCode,
    };
    const response = await adapter.fetch({
      method: 'POST',
      path,
      queryParams,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.UserDTO>;
}

export interface RevokePortalOnlyAccessForUserParams {
    path: { accountId: string };
}

/**
 * Revoke portal only access for user
 * @forge-scopes-asApp read:jira-user
 * @forge-scopes-asUser read:jira-user
 */
export async function revokePortalOnlyAccessForUser(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: RevokePortalOnlyAccessForUserParams): Promise<Record<string, unknown>> {
    const path = `/rest/servicedeskapi/customer/user/${params.path.accountId}/revoke-portal-only-access`;
    const response = await adapter.fetch({
      method: 'PUT',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Record<string, unknown>>;
}

/**
 * Get info
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getInfo(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }): Promise<Types.SoftwareInfoDTO> {
    const path = '/rest/servicedeskapi/info';
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.SoftwareInfoDTO>;
}

export interface GetInsightWorkspacesParams {
    start?: number;
    limit?: number;
}

/**
 * Get insight workspaces
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getInsightWorkspaces(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetInsightWorkspacesParams): Promise<Types.PagedDTOInsightWorkspaceDTO> {
    const path = '/rest/servicedeskapi/insight/workspace';
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOInsightWorkspaceDTO>;
}

export interface GetArticlesGlobalParams {
    query: string;
    highlight: boolean;
    start?: number;
    limit?: number;
    cursor?: string;
    prev?: boolean;
}

/**
 * Get articles
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getArticlesGlobal(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetArticlesGlobalParams): Promise<Types.PagedDTOArticleDTO> {
    const path = '/rest/servicedeskapi/knowledgebase/article';
    const queryParams = {
      query: params.query,
      highlight: params.highlight,
      start: params.start,
      limit: params.limit,
      cursor: params.cursor,
      prev: params.prev,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOArticleDTO>;
}

export interface GetOrganizationsGlobalParams {
    start?: number;
    limit?: number;
    accountId?: string;
}

/**
 * Get organizations
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getOrganizationsGlobal(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetOrganizationsGlobalParams): Promise<Types.PagedDTOOrganizationDTO> {
    const path = '/rest/servicedeskapi/organization';
    const queryParams = {
      start: params.start,
      limit: params.limit,
      accountId: params.accountId,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOOrganizationDTO>;
}

export interface CreateOrganizationParams {
    body?: OrganizationCreateDTO;
}

/**
 * Create organization
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function createOrganization(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: CreateOrganizationParams): Promise<Types.OrganizationDTO> {
    const path = '/rest/servicedeskapi/organization';
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.OrganizationDTO>;
}

export interface GetOrganizationParams {
    path: { organizationId: string };
}

/**
 * Get organization
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getOrganization(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetOrganizationParams): Promise<Types.OrganizationDTO> {
    const path = `/rest/servicedeskapi/organization/${params.path.organizationId}`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.OrganizationDTO>;
}

export interface DeleteOrganizationParams {
    path: { organizationId: string };
}

/**
 * Delete organization
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function deleteOrganization(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: DeleteOrganizationParams): Promise<void> {
    const path = `/rest/servicedeskapi/organization/${params.path.organizationId}`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetPropertiesKeysForOrgParams {
    path: { organizationId: string };
}

/**
 * Get properties keys
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getPropertiesKeysForOrg(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetPropertiesKeysForOrgParams): Promise<Types.PropertyKeys> {
    const path = `/rest/servicedeskapi/organization/${params.path.organizationId}/property`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PropertyKeys>;
}

export interface GetPropertyForOrgParams {
    path: { organizationId: string; propertyKey: string };
}

/**
 * Get property
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getPropertyForOrg(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetPropertyForOrgParams): Promise<Types.EntityProperty> {
    const path = `/rest/servicedeskapi/organization/${params.path.organizationId}/property/${params.path.propertyKey}`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.EntityProperty>;
}

export interface SetPropertyForOrgParams {
    path: { organizationId: string; propertyKey: string };
    body?: Record<string, unknown>;
}

/**
 * Set property
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function setPropertyForOrg(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: SetPropertyForOrgParams): Promise<Record<string, unknown>> {
    const path = `/rest/servicedeskapi/organization/${params.path.organizationId}/property/${params.path.propertyKey}`;
    const response = await adapter.fetch({
      method: 'PUT',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Record<string, unknown>>;
}

export interface DeletePropertyForOrgParams {
    path: { organizationId: string; propertyKey: string };
}

/**
 * Delete property
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function deletePropertyForOrg(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: DeletePropertyForOrgParams): Promise<void> {
    const path = `/rest/servicedeskapi/organization/${params.path.organizationId}/property/${params.path.propertyKey}`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetUsersInOrganizationParams {
    path: { organizationId: string };
    start?: number;
    limit?: number;
}

/**
 * Get users in organization
 * @forge-scopes-asApp read:jira-work, read:jira-user
 * @forge-scopes-asUser read:jira-work, read:jira-user
 */
export async function getUsersInOrganization(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetUsersInOrganizationParams): Promise<Types.PagedDTOUserDTO> {
    const path = `/rest/servicedeskapi/organization/${params.path.organizationId}/user`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOUserDTO>;
}

export interface AddUsersToOrganizationParams {
    path: { organizationId: string };
    body?: UsersOrganizationUpdateDTO;
}

/**
 * Add users to organization
 * @forge-scopes-asApp write:jira-work, read:jira-user
 * @forge-scopes-asUser write:jira-work, read:jira-user
 */
export async function addUsersToOrganization(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: AddUsersToOrganizationParams): Promise<void> {
    const path = `/rest/servicedeskapi/organization/${params.path.organizationId}/user`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface RemoveUsersFromOrganizationParams {
    path: { organizationId: string };
    body?: UsersOrganizationUpdateDTO;
}

/**
 * Remove users from organization
 * @forge-scopes-asApp write:jira-work, read:jira-user
 * @forge-scopes-asUser write:jira-work, read:jira-user
 */
export async function removeUsersFromOrganization(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: RemoveUsersFromOrganizationParams): Promise<void> {
    const path = `/rest/servicedeskapi/organization/${params.path.organizationId}/user`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetCustomerRequestsParams {
    searchTerm?: string;
    requestOwnership?: Array<string>;
    requestStatus?: string;
    approvalStatus?: string;
    organizationId?: number;
    serviceDeskId?: number;
    requestTypeId?: number;
    expand?: Array<string>;
    start?: number;
    limit?: number;
}

/**
 * Get customer requests
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getCustomerRequests(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetCustomerRequestsParams): Promise<Types.PagedDTOCustomerRequestDTO> {
    const path = '/rest/servicedeskapi/request';
    const queryParams = {
      searchTerm: params.searchTerm,
      requestOwnership: params.requestOwnership,
      requestStatus: params.requestStatus,
      approvalStatus: params.approvalStatus,
      organizationId: params.organizationId,
      serviceDeskId: params.serviceDeskId,
      requestTypeId: params.requestTypeId,
      expand: params.expand,
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOCustomerRequestDTO>;
}

export interface CreateCustomerRequestParams {
    body?: RequestCreateDTO;
}

/**
 * Create customer request
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function createCustomerRequest(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: CreateCustomerRequestParams): Promise<Types.CustomerRequestDTO> {
    const path = '/rest/servicedeskapi/request';
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.CustomerRequestDTO>;
}

export interface GetCustomerRequestByIdOrKeyParams {
    path: { issueIdOrKey: string };
    expand?: Array<string>;
}

/**
 * Get customer request by id or key
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getCustomerRequestByIdOrKey(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetCustomerRequestByIdOrKeyParams): Promise<Types.CustomerRequestDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}`;
    const queryParams = {
      expand: params.expand,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.CustomerRequestDTO>;
}

export interface GetApprovalsParams {
    path: { issueIdOrKey: string };
    start?: number;
    limit?: number;
}

/**
 * Get approvals
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getApprovals(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetApprovalsParams): Promise<Types.PagedDTOApprovalDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/approval`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOApprovalDTO>;
}

export interface GetApprovalByIdParams {
    path: { issueIdOrKey: string; approvalId: string };
}

/**
 * Get approval by id
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getApprovalById(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetApprovalByIdParams): Promise<Types.ApprovalDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/approval/${params.path.approvalId}`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.ApprovalDTO>;
}

export interface AnswerApprovalParams {
    path: { issueIdOrKey: string; approvalId: string };
    body?: ApprovalDecisionRequestDTO;
}

/**
 * Answer approval
 * @forge-scopes-asApp read:jira-work
 */
export async function answerApproval(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: AnswerApprovalParams): Promise<Types.ApprovalDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/approval/${params.path.approvalId}`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.ApprovalDTO>;
}

export interface GetAttachmentsForRequestParams {
    path: { issueIdOrKey: string };
    start: number;
    limit: number;
}

/**
 * Get attachments for request
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getAttachmentsForRequest(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetAttachmentsForRequestParams): Promise<Types.PagedDTOAttachmentDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/attachment`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOAttachmentDTO>;
}

export interface CreateCommentWithAttachmentParams {
    path: { issueIdOrKey: string };
    body?: AttachmentCreateDTO;
}

/**
 * Create comment with attachment
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function createCommentWithAttachment(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: CreateCommentWithAttachmentParams): Promise<Types.AttachmentCreateResultDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/attachment`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.AttachmentCreateResultDTO>;
}

export interface GetAttachmentContentParams {
    path: { issueIdOrKey: string; attachmentId: string };
}

/**
 * Get attachment content
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getAttachmentContent(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetAttachmentContentParams): Promise<Record<string, unknown>> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/attachment/${params.path.attachmentId}`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Record<string, unknown>>;
}

export interface GetAttachmentThumbnailParams {
    path: { issueIdOrKey: string; attachmentId: string };
}

/**
 * Get attachment thumbnail
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getAttachmentThumbnail(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetAttachmentThumbnailParams): Promise<Record<string, unknown>> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/attachment/${params.path.attachmentId}/thumbnail`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Record<string, unknown>>;
}

export interface GetRequestCommentsParams {
    path: { issueIdOrKey: string };
    public?: boolean;
    internal?: boolean;
    expand?: Array<string>;
    start?: number;
    limit?: number;
}

/**
 * Get request comments
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getRequestComments(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetRequestCommentsParams): Promise<Types.PagedDTOCommentDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/comment`;
    const queryParams = {
      public: params.public,
      internal: params.internal,
      expand: params.expand,
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOCommentDTO>;
}

export interface CreateRequestCommentParams {
    path: { issueIdOrKey: string };
    body?: CommentCreateDTO;
}

/**
 * Create request comment
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function createRequestComment(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: CreateRequestCommentParams): Promise<Types.CommentDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/comment`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.CommentDTO>;
}

export interface GetRequestCommentByIdParams {
    path: { issueIdOrKey: string; commentId: string };
    expand?: Array<string>;
}

/**
 * Get request comment by id
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getRequestCommentById(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetRequestCommentByIdParams): Promise<Types.CommentDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/comment/${params.path.commentId}`;
    const queryParams = {
      expand: params.expand,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.CommentDTO>;
}

export interface GetCommentAttachmentsParams {
    path: { issueIdOrKey: string; commentId: string };
    start?: number;
    limit?: number;
}

/**
 * Get comment attachments
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getCommentAttachments(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetCommentAttachmentsParams): Promise<Types.PagedDTOAttachmentDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/comment/${params.path.commentId}/attachment`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOAttachmentDTO>;
}

export interface GetSubscriptionStatusParams {
    path: { issueIdOrKey: string };
}

/**
 * Get subscription status
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getSubscriptionStatus(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetSubscriptionStatusParams): Promise<Types.RequestNotificationSubscriptionDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/notification`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.RequestNotificationSubscriptionDTO>;
}

export interface SubscribeParams {
    path: { issueIdOrKey: string };
}

/**
 * Subscribe
 * @forge-scopes-asApp read:jira-work
 */
export async function subscribe(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: SubscribeParams): Promise<void> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/notification`;
    const response = await adapter.fetch({
      method: 'PUT',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface UnsubscribeParams {
    path: { issueIdOrKey: string };
}

/**
 * Unsubscribe
 * @forge-scopes-asApp read:jira-work
 */
export async function unsubscribe(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: UnsubscribeParams): Promise<void> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/notification`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetRequestParticipantsParams {
    path: { issueIdOrKey: string };
    start?: number;
    limit?: number;
}

/**
 * Get request participants
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getRequestParticipants(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetRequestParticipantsParams): Promise<Types.PagedDTOUserDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/participant`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOUserDTO>;
}

export interface AddRequestParticipantsParams {
    path: { issueIdOrKey: string };
    body?: RequestParticipantUpdateDTO;
}

/**
 * Add request participants
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function addRequestParticipants(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: AddRequestParticipantsParams): Promise<Types.PagedDTOUserDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/participant`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOUserDTO>;
}

export interface RemoveRequestParticipantsParams {
    path: { issueIdOrKey: string };
    body?: RequestParticipantUpdateDTO;
}

/**
 * Remove request participants
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function removeRequestParticipants(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: RemoveRequestParticipantsParams): Promise<Types.PagedDTOUserDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/participant`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOUserDTO>;
}

export interface GetSlaInformationParams {
    path: { issueIdOrKey: string };
    start?: number;
    limit?: number;
}

/**
 * Get sla information
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getSlaInformation(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetSlaInformationParams): Promise<Types.PagedDTOSlaInformationDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/sla`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOSlaInformationDTO>;
}

export interface GetSlaInformationByIdParams {
    path: { issueIdOrKey: string; slaMetricId: string };
}

/**
 * Get sla information by id
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getSlaInformationById(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetSlaInformationByIdParams): Promise<Types.SlaInformationDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/sla/${params.path.slaMetricId}`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.SlaInformationDTO>;
}

export interface GetCustomerRequestStatusParams {
    path: { issueIdOrKey: string };
    start?: number;
    limit?: number;
}

/**
 * Get customer request status
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getCustomerRequestStatus(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetCustomerRequestStatusParams): Promise<Types.PagedDTOCustomerRequestStatusDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/status`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOCustomerRequestStatusDTO>;
}

export interface GetCustomerTransitionsParams {
    path: { issueIdOrKey: string };
    start?: number;
    limit?: number;
}

/**
 * Get customer transitions
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getCustomerTransitions(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetCustomerTransitionsParams): Promise<Types.PagedDTOCustomerTransitionDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/transition`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOCustomerTransitionDTO>;
}

export interface PerformCustomerTransitionParams {
    path: { issueIdOrKey: string };
    body?: CustomerTransitionExecutionDTO;
}

/**
 * Perform customer transition
 * @forge-scopes-asApp read:jira-work
 */
export async function performCustomerTransition(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: PerformCustomerTransitionParams): Promise<void> {
    const path = `/rest/servicedeskapi/request/${params.path.issueIdOrKey}/transition`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetFeedbackParams {
    path: { requestIdOrKey: string };
}

/**
 * Get feedback
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getFeedback(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetFeedbackParams): Promise<Types.CSATFeedbackFullDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.requestIdOrKey}/feedback`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.CSATFeedbackFullDTO>;
}

export interface PostFeedbackParams {
    path: { requestIdOrKey: string };
    body?: CSATFeedbackFullDTO;
}

/**
 * Post feedback
 * @forge-scopes-asApp read:jira-work
 */
export async function postFeedback(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: PostFeedbackParams): Promise<Types.CSATFeedbackFullDTO> {
    const path = `/rest/servicedeskapi/request/${params.path.requestIdOrKey}/feedback`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.CSATFeedbackFullDTO>;
}

export interface DeleteFeedbackParams {
    path: { requestIdOrKey: string };
}

/**
 * Delete feedback
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function deleteFeedback(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: DeleteFeedbackParams): Promise<Record<string, unknown>> {
    const path = `/rest/servicedeskapi/request/${params.path.requestIdOrKey}/feedback`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Record<string, unknown>>;
}

export interface GetAllRequestTypesParams {
    searchQuery?: string;
    serviceDeskId?: Array<number>;
    start?: number;
    limit?: number;
    expand?: Array<string>;
    includeHiddenRequestTypesInSearch?: boolean;
    restrictionStatus?: string;
}

/**
 * Get all request types
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getAllRequestTypes(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetAllRequestTypesParams): Promise<Types.PagedDTORequestTypeDTO> {
    const path = '/rest/servicedeskapi/requesttype';
    const queryParams = {
      searchQuery: params.searchQuery,
      serviceDeskId: params.serviceDeskId,
      start: params.start,
      limit: params.limit,
      expand: params.expand,
      includeHiddenRequestTypesInSearch: params.includeHiddenRequestTypesInSearch,
      restrictionStatus: params.restrictionStatus,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTORequestTypeDTO>;
}

export interface GetServiceDesksParams {
    start?: number;
    limit?: number;
}

/**
 * Get service desks
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getServiceDesks(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetServiceDesksParams): Promise<Types.PagedDTOServiceDeskDTO> {
    const path = '/rest/servicedeskapi/servicedesk';
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOServiceDeskDTO>;
}

export interface GetServiceDeskByIdParams {
    path: { serviceDeskId: string };
}

/**
 * Get service desk by id
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getServiceDeskById(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetServiceDeskByIdParams): Promise<Types.ServiceDeskDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.ServiceDeskDTO>;
}

export interface AttachTemporaryFileParams {
    path: { serviceDeskId: string };
    body?: Record<string, unknown>;
}

/**
 * Attach temporary file
 * @forge-scopes-asApp read:jira-work
 */
export async function attachTemporaryFile(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: AttachTemporaryFileParams): Promise<void> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/attachTemporaryFile`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetCustomersParams {
    path: { serviceDeskId: string };
    query?: string;
    start?: number;
    limit?: number;
}

/**
 * Get customers
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getCustomers(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetCustomersParams): Promise<Types.PagedDTOUserDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/customer`;
    const queryParams = {
      query: params.query,
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOUserDTO>;
}

export interface AddCustomersParams {
    path: { serviceDeskId: string };
    body?: ServiceDeskCustomerDTO;
}

/**
 * Add customers
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function addCustomers(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: AddCustomersParams): Promise<void> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/customer`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface RemoveCustomersParams {
    path: { serviceDeskId: string };
    body?: ServiceDeskCustomerDTO;
}

/**
 * Remove customers
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function removeCustomers(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: RemoveCustomersParams): Promise<void> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/customer`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface InviteCustomerParams {
    path: { serviceDeskId: string };
    strictConflictStatusCode?: boolean;
    body?: ServiceDeskCustomerInviteDTO;
}

/**
 * Invite customer
 * @forge-scopes-asApp read:jira-work
 */
export async function inviteCustomer(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: InviteCustomerParams): Promise<void> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/customer/invite`;
    const queryParams = {
      strictConflictStatusCode: params.strictConflictStatusCode,
    };
    const response = await adapter.fetch({
      method: 'POST',
      path,
      queryParams,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetArticlesForServiceDeskParams {
    path: { serviceDeskId: string };
    query: string;
    highlight?: boolean;
    start?: number;
    limit?: number;
    cursor?: string;
    prev?: boolean;
}

/**
 * Get articles
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getArticlesForServiceDesk(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetArticlesForServiceDeskParams): Promise<Types.PagedDTOArticleDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/knowledgebase/article`;
    const queryParams = {
      query: params.query,
      highlight: params.highlight,
      start: params.start,
      limit: params.limit,
      cursor: params.cursor,
      prev: params.prev,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOArticleDTO>;
}

export interface GetOrganizationsForServiceDeskParams {
    path: { serviceDeskId: string };
    start?: number;
    limit?: number;
    accountId?: string;
}

/**
 * Get organizations
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getOrganizationsForServiceDesk(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetOrganizationsForServiceDeskParams): Promise<Types.PagedDTOOrganizationDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/organization`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
      accountId: params.accountId,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOOrganizationDTO>;
}

export interface AddOrganizationParams {
    path: { serviceDeskId: string };
    body?: OrganizationServiceDeskUpdateDTO;
}

/**
 * Add organization
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function addOrganization(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: AddOrganizationParams): Promise<void> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/organization`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface RemoveOrganizationParams {
    path: { serviceDeskId: string };
    body?: OrganizationServiceDeskUpdateDTO;
}

/**
 * Remove organization
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function removeOrganization(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: RemoveOrganizationParams): Promise<void> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/organization`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetQueuesParams {
    path: { serviceDeskId: string };
    includeCount?: boolean;
    start?: number;
    limit?: number;
}

/**
 * Get queues
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getQueues(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetQueuesParams): Promise<Types.PagedDTOQueueDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/queue`;
    const queryParams = {
      includeCount: params.includeCount,
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOQueueDTO>;
}

export interface GetQueueParams {
    path: { serviceDeskId: string; queueId: string };
    includeCount?: boolean;
}

/**
 * Get queue
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getQueue(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetQueueParams): Promise<Types.QueueDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/queue/${params.path.queueId}`;
    const queryParams = {
      includeCount: params.includeCount,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.QueueDTO>;
}

export interface GetIssuesInQueueParams {
    path: { serviceDeskId: string; queueId: string };
    start?: number;
    limit?: number;
}

/**
 * Get issues in queue
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getIssuesInQueue(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetIssuesInQueueParams): Promise<Types.PagedDTOIssueBean> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/queue/${params.path.queueId}/issue`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTOIssueBean>;
}

export interface GetRequestTypesParams {
    path: { serviceDeskId: string };
    groupId?: number;
    expand?: Array<string>;
    searchQuery?: string;
    start?: number;
    limit?: number;
    includeHiddenRequestTypesInSearch?: boolean;
    restrictionStatus?: string;
}

/**
 * Get request types
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getRequestTypes(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetRequestTypesParams): Promise<Types.PagedDTORequestTypeDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype`;
    const queryParams = {
      groupId: params.groupId,
      expand: params.expand,
      searchQuery: params.searchQuery,
      start: params.start,
      limit: params.limit,
      includeHiddenRequestTypesInSearch: params.includeHiddenRequestTypesInSearch,
      restrictionStatus: params.restrictionStatus,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTORequestTypeDTO>;
}

export interface CreateRequestTypeParams {
    path: { serviceDeskId: string };
    body?: RequestTypeCreateDTO;
}

/**
 * Create request type
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function createRequestType(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: CreateRequestTypeParams): Promise<Types.RequestTypeDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.RequestTypeDTO>;
}

export interface CheckRequestTypePermissionsParams {
    path: { serviceDeskId: string };
    body?: RequestTypePermissionCheckRequestDTO;
}

/**
 * Check request type permissions
 * @forge-scopes-asApp read:jira-work
 */
export async function checkRequestTypePermissions(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: CheckRequestTypePermissionsParams): Promise<Types.RequestTypePermissionCheckResponse> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype/permissions/check`;
    const response = await adapter.fetch({
      method: 'POST',
      path,
      body: params.body,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.RequestTypePermissionCheckResponse>;
}

export interface GetRequestTypeByIdParams {
    path: { serviceDeskId: string; requestTypeId: string };
    expand?: Array<string>;
}

/**
 * Get request type by id
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getRequestTypeById(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetRequestTypeByIdParams): Promise<Types.RequestTypeDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype/${params.path.requestTypeId}`;
    const queryParams = {
      expand: params.expand,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.RequestTypeDTO>;
}

export interface DeleteRequestTypeParams {
    path: { serviceDeskId: string; requestTypeId: string };
}

/**
 * Delete request type
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function deleteRequestType(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: DeleteRequestTypeParams): Promise<void> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype/${params.path.requestTypeId}`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetRequestTypeFieldsParams {
    path: { serviceDeskId: string; requestTypeId: string };
    expand?: Array<string>;
}

/**
 * Get request type fields
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getRequestTypeFields(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetRequestTypeFieldsParams): Promise<Types.CustomerRequestCreateMetaDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype/${params.path.requestTypeId}/field`;
    const queryParams = {
      expand: params.expand,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.CustomerRequestCreateMetaDTO>;
}

export interface GetPropertiesKeysForRequestTypeParams {
    path: { requestTypeId: string; serviceDeskId: string };
}

/**
 * Get properties keys
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getPropertiesKeysForRequestType(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetPropertiesKeysForRequestTypeParams): Promise<Types.PropertyKeys> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype/${params.path.requestTypeId}/property`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PropertyKeys>;
}

export interface GetPropertyForRequestTypeParams {
    path: { serviceDeskId: string; requestTypeId: string; propertyKey: string };
}

/**
 * Get property
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getPropertyForRequestType(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetPropertyForRequestTypeParams): Promise<Types.EntityProperty> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype/${params.path.requestTypeId}/property/${params.path.propertyKey}`;
    const response = await adapter.fetch({
      method: 'GET',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.EntityProperty>;
}

export interface SetPropertyForRequestTypeParams {
    path: { serviceDeskId: string; requestTypeId: string; propertyKey: string };
}

/**
 * Set property
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function setPropertyForRequestType(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: SetPropertyForRequestTypeParams): Promise<Record<string, unknown>> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype/${params.path.requestTypeId}/property/${params.path.propertyKey}`;
    const response = await adapter.fetch({
      method: 'PUT',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Record<string, unknown>>;
}

export interface DeletePropertyForRequestTypeParams {
    path: { serviceDeskId: string; requestTypeId: string; propertyKey: string };
}

/**
 * Delete property
 * @forge-scopes-asApp write:jira-work
 * @forge-scopes-asUser write:jira-work
 */
export async function deletePropertyForRequestType(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: DeletePropertyForRequestTypeParams): Promise<void> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttype/${params.path.requestTypeId}/property/${params.path.propertyKey}`;
    const response = await adapter.fetch({
      method: 'DELETE',
      path,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
}

export interface GetRequestTypeGroupsParams {
    path: { serviceDeskId: string };
    start?: number;
    limit?: number;
}

/**
 * Get request type groups
 * @forge-scopes-asApp read:jira-work
 * @forge-scopes-asUser read:jira-work
 */
export async function getRequestTypeGroups(adapter: ForgeAdapter, authContext: AuthContext = { type: 'asApp' }, params: GetRequestTypeGroupsParams): Promise<Types.PagedDTORequestTypeGroupDTO> {
    const path = `/rest/servicedeskapi/servicedesk/${params.path.serviceDeskId}/requesttypegroup`;
    const queryParams = {
      start: params.start,
      limit: params.limit,
    };
    const response = await adapter.fetch({
      method: 'GET',
      path,
      queryParams,
      authContext,
    });
    if (!response.ok) throw await ForgeApiError.fromResponse(response, path);
    return response.json() as Promise<Types.PagedDTORequestTypeGroupDTO>;
}
