// Generated by @forge-clients/generator — DO NOT EDIT
// Source: Jira Service Management Cloud REST API
/* eslint-disable */
// prettier-ignore
export interface AdditionalCommentDTO {
    /** Content of the comment. */
    body?: string;
}

export interface ApprovalDTO {
    /** The REST API URL of the approval. */
    _links?: SelfLinkDTO;
    /** Detailed list of the users who must provide a response to the approval. */
    approvers?: Array<ApproverDTO>;
    /** Indicates whether the user making the request is one of the approvers and can respond to the approval (true) or not (false). */
    canAnswerApproval?: boolean;
    /** Date the approval was completed. */
    completedDate?: DateDTO;
    /** Date the approval was created. */
    createdDate?: DateDTO;
    /** Outcome of the approval, based on the approvals provided by all approvers. */
    finalDecision?: "approved" | "declined" | "pending";
    /** ID of the approval. */
    id?: string;
    /** Description of the approval being sought or provided. */
    name?: string;
}

export interface ApprovalDecisionRequestDTO {
    /** Response to the approval request. */
    decision?: "approve" | "decline";
}

export interface ApproverDTO {
    /** Details of the User who is providing approval. */
    approver?: UserDTO;
    /** Decision made by the approver. */
    approverDecision?: "approved" | "declined" | "pending";
}

export interface ArticleDTO {
    content?: ContentDTO;
    /** Excerpt of the article which matches the given query string. */
    excerpt?: string;
    /** Source of the article. */
    source?: SourceDTO;
    /** Title of the article. */
    title?: string;
}

/** Details of an Assets workspace ID. */
export interface AssetsWorkspaceDTO {
    /** The workspace ID used as the identifier to access the Assets REST API. */
    workspaceId?: string;
}

export interface AttachmentCreateDTO {
    /** Additional content of the comment */
    additionalComment?: AdditionalCommentDTO;
    /** Controls whether the comment and its attachments are visible to customers */
    public?: boolean;
    /** List of IDs for the temporary attachments to be added to the customer request. */
    temporaryAttachmentIds?: Array<string>;
}

export interface AttachmentCreateResultDTO {
    /** List of the attachments added. */
    attachments?: PagedDTOAttachmentDTO;
    /** Details of the comment included with the attachments. */
    comment?: CommentDTO;
}

export interface AttachmentDTO {
    /** Various URLs for the attachment. */
    _links?: AttachmentLinkDTO;
    /** Details of the user who attached the file. */
    author?: UserDTO;
    /** Date the attachment was added. */
    created?: DateDTO;
    /** Filename of the item attached. */
    filename?: string;
    /** MIME type of the attachment. */
    mimeType?: string;
    /** Size of the attachment in bytes. */
    size?: number;
}

export interface AttachmentLinkDTO {
    /** URL for the attachment. */
    content?: string;
    /** REST API URL for the attachment */
    jiraRest?: string;
    self?: string;
    /** URL for the attachment's thumbnail image. */
    thumbnail?: string;
}

export interface AvatarUrlsBean {
    /** The URL of the item's 16x16 pixel avatar. */
    "16x16"?: string;
    /** The URL of the item's 24x24 pixel avatar. */
    "24x24"?: string;
    /** The URL of the item's 32x32 pixel avatar. */
    "32x32"?: string;
    /** The URL of the item's 48x48 pixel avatar. */
    "48x48"?: string;
}

export interface CSATFeedbackFullDTO {
    /** (Optional) The comment provided with this feedback. */
    comment?: AdditionalCommentDTO;
    /** A numeric representation of the rating, this must be an integer value between 1 and 5. */
    rating?: number;
    /** Indicates the type of feedback, supported values: `csat`. */
    type?: string;
}

/** A change item. */
export interface ChangeDetails {
    /** The name of the field changed. */
    readonly field?: string;
    /** The ID of the field changed. */
    readonly fieldId?: string;
    /** The type of the field changed. */
    readonly fieldtype?: string;
    /** The details of the original value. */
    readonly from?: string;
    /** The details of the original value as a string. */
    readonly fromString?: string;
    /** The details of the new value. */
    readonly to?: string;
    /** The details of the new value as a string. */
    readonly toString?: string;
}

/** A log of changes made to issue fields. Changelogs related to workflow associations are currently being deprecated. */
export interface Changelog {
    /** The user who made the change. */
    readonly author?: UserDetails;
    /** The date on which the change took place. */
    readonly created?: string;
    /** The history metadata associated with the changed. */
    readonly historyMetadata?: HistoryMetadata;
    /** The ID of the changelog. */
    readonly id?: string;
    /** The list of items changed. */
    readonly items?: Array<ChangeDetails>;
}

export interface CommentCreateDTO {
    /** Content of the comment. */
    body?: string;
    /** Indicates whether the comment is public (true) or private/internal (false). */
    public?: boolean;
}

export interface CommentDTO {
    /** List of items that can be expanded in the response by specifying the expand query parameter. */
    _expands?: Array<string>;
    /** REST API URL link to the comment. */
    _links?: SelfLinkDTO;
    /** List of the attachments included in the comment. */
    attachments?: PagedDTOAttachmentDTO;
    /** Details of the customer who authored the comment. */
    author?: UserDTO;
    /** Content of the comment. */
    body?: string;
    /** Date the comment was created. */
    created?: DateDTO;
    /** ID of the comment. */
    id?: string;
    /** Indicates whether the comment is public (true) or private/internal (false). */
    public?: boolean;
    /** The rendered body of the comment. */
    renderedBody?: RenderedValueDTO;
}

export interface ContentDTO {
    /** Url containing the body of the article (without title), suitable for rendering in an iframe */
    iframeSrc?: string;
}

export interface CustomerCreateDTO {
    /** Customer's name for display in the UI. */
    displayName?: string;
    /** Customer's email address. */
    email?: string;
    /** Deprecated, please use 'displayName'. */
    fullName?: string;
}

export interface CustomerRequestActionDTO {
    /** Indicates whether the user can undertake the action (true) or not (false). */
    allowed?: boolean;
}

export interface CustomerRequestActionsDTO {
    /** Action of adding attachments to a request. */
    addAttachment?: CustomerRequestActionDTO;
    /** Action of adding comments to a request. */
    addComment?: CustomerRequestActionDTO;
    /** Action of adding participants to a request. */
    addParticipant?: CustomerRequestActionDTO;
    /** Action of removing participants from a request. */
    removeParticipant?: CustomerRequestActionDTO;
}

export interface CustomerRequestCreateMetaDTO {
    /** Flag indicating if participants can be added to a request (true) or not. */
    canAddRequestParticipants?: boolean;
    /** Flag indicating if a request can be raised on behalf of another user (true) or not. */
    canRaiseOnBehalfOf?: boolean;
    /** List of the fields included in this request. */
    requestTypeFields?: Array<RequestTypeFieldDTO>;
}

export interface CustomerRequestDTO {
    /** List of items that can be expanded in the response by specifying the expand query parameter. */
    _expands?: Array<string>;
    /** List of links associated with the request. */
    _links?: CustomerRequestLinkDTO;
    /** List of actions that the user can take on the request. */
    actions?: CustomerRequestActionsDTO;
    /** List of attachments included with the request. */
    attachments?: PagedDTOAttachmentDTO;
    /** List of comments included with the request. */
    comments?: PagedDTOCommentDTO;
    /** Date on which the request was created. */
    createdDate?: DateDTO;
    /** Status of the request. */
    currentStatus?: CustomerRequestStatusDTO;
    /** ID of the request, as the peer issue ID. */
    issueId?: string;
    /** Key of the request, as the peer issue key. */
    issueKey?: string;
    /** Expandable details of the customers participating in the request. */
    participants?: PagedDTOUserDTO;
    /** Details of the customer reporting the request. */
    reporter?: UserDTO;
    /** JSON map of Jira field IDs and their values representing the content of the request. This list does not include hidden fields. */
    requestFieldValues?: Array<CustomerRequestFieldValueDTO>;
    /** Expandable details of the request type. */
    requestType?: RequestTypeDTO;
    /** ID of the request type for the request. */
    requestTypeId?: string;
    /** Expandable details of the service desk. */
    serviceDesk?: ServiceDeskDTO;
    /** ID of the service desk the request belongs to. */
    serviceDeskId?: string;
    /** Expandable details of the SLAs relating to the request. */
    sla?: PagedDTOSlaInformationDTO;
    /** Expandable details of the request's status history. */
    status?: PagedDTOCustomerRequestStatusDTO;
    /** Summary of the request created */
    summary?: string;
}

export interface CustomerRequestFieldValueDTO {
    /** ID of the field. */
    fieldId?: string;
    /** Text label for the field. */
    label?: string;
    /** Value of the field rendered in the UI. */
    renderedValue?: Record<string, unknown>;
    /** Value of the field. */
    value?: Record<string, unknown>;
}

export interface CustomerRequestLinkDTO {
    /** Jira agent view URL for the request. */
    agent?: string;
    /** REST API URL for the request. */
    jiraRest?: string;
    self?: string;
    /** Web URL for the request. */
    web?: string;
}

export interface CustomerRequestStatusDTO {
    /** Name of the status condition. */
    status?: string;
    /** Status category the status belongs to. */
    statusCategory?: "UNDEFINED" | "NEW" | "INDETERMINATE" | "DONE";
    /** Date on which the status was attained. */
    statusDate?: DateDTO;
}

export interface CustomerTransitionDTO {
    /** ID of the transition. */
    id?: string;
    /** Name of the transition. */
    name?: string;
}

export interface CustomerTransitionExecutionDTO {
    /** Comment explaining the reason for the transition. */
    additionalComment?: AdditionalCommentDTO;
    /** ID of the transition to be performed. */
    id?: string;
}

export interface DateDTO {
    /** Date as the number of milliseconds that have elapsed since 00:00:00 Coordinated Universal Time (UTC), 1 January 1970. */
    epochMillis?: number;
    /** Date in a user-friendly text format. */
    friendly?: string;
    /** Date in ISO8601 format. */
    iso8601?: string;
    /** Date in the format used in the Jira REST APIs, which is ISO8601 format but extended with milliseconds. For example, 2016-09-28T23:08:32.097+1000. */
    jira?: string;
}

export interface DurationDTO {
    /** Duration in a user-friendly text format. */
    friendly?: string;
    /** Duration in milliseconds. */
    millis?: number;
}

/** An entity property, for more information see [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/). */
export interface EntityProperty {
    /** The key of the property. Required on create and update. */
    key?: string;
    /** The value of the property. Required on create and update. */
    value?: Record<string, unknown>;
}

export interface ErrorResponse {
    errorMessages?: Array<string>;
    errors?: Record<string, string>;
    status?: number;
    message?: string;
}

export interface Expandable {
    _expands?: Array<string>;
}

/** The metadata describing an issue field. */
export interface FieldMetadata {
    /** The list of values allowed in the field. */
    readonly allowedValues?: Array<Record<string, unknown>>;
    /** The URL that can be used to automatically complete the field. */
    readonly autoCompleteUrl?: string;
    /** The configuration properties. */
    readonly configuration?: Record<string, Record<string, unknown>>;
    /** The default value of the field. */
    readonly defaultValue?: Record<string, unknown>;
    /** Whether the field has a default value. */
    readonly hasDefaultValue?: boolean;
    /** The key of the field. */
    readonly key: string;
    /** The name of the field. */
    readonly name: string;
    /** The list of operations that can be performed on the field. */
    readonly operations: Array<string>;
    /** Whether the field is required. */
    readonly required: boolean;
    /** The data type of the field. */
    readonly schema: JsonTypeBean;
}

export type Form = Record<string, unknown>;

export interface FormAnswer {
    /** Answer in Atlassian Document Format (ADF) */
    adf?: JsonNode;
    /** IDs of selected choices */
    choices?: Array<string>;
    /** Answer in date format (yyyy-MM-dd) */
    date?: string;
    /** The IDs of files to be attached to the form that are obtained by calling the ‘attach temporary file’ endpoint on the corresponding service desk. */
    files?: Array<string>;
    /** Answer in free text format */
    text?: string;
    /** Answer in timestamp format (HH:mm) */
    time?: string;
    /** IDs of selected users */
    users?: Array<string>;
}

/** Details of issue history metadata. */
export type HistoryMetadata = Record<string, unknown>;
/** Details of user or system associated with a issue history metadata item. */
export type HistoryMetadataParticipant = Record<string, unknown>;

export interface I18nErrorMessage {
    i18nKey?: string;
    parameters?: Array<string>;
}

export interface IncludedFields {
    actuallyIncluded?: Array<string>;
    excluded?: Array<string>;
    included?: Array<string>;
}

export interface InputStreamSource {
    inputStream?: Record<string, unknown>;
}

/** Details of an insight workspace ID. */
export interface InsightWorkspaceDTO {
    /** The workspace ID used as the identifier to access the Insight REST API. */
    workspaceId?: string;
}

/** Details about an issue. */
export interface IssueBean {
    /** Details of changelogs associated with the issue. */
    readonly changelog?: PageOfChangelogs;
    /** The metadata for the fields on the issue that can be amended. */
    readonly editmeta?: IssueUpdateMetadata;
    /** Expand options that include additional issue details in the response. */
    readonly expand?: string;
    fields?: Record<string, Record<string, unknown>>;
    fieldsToInclude?: IncludedFields;
    /** The ID of the issue. */
    readonly id?: string;
    /** The key of the issue. */
    readonly key?: string;
    /** The ID and name of each field present on the issue. */
    readonly names?: Record<string, string>;
    /** The operations that can be performed on the issue. */
    readonly operations?: Operations;
    /** Details of the issue properties identified in the request. */
    readonly properties?: Record<string, Record<string, unknown>>;
    /** The rendered value of each field present on the issue. */
    readonly renderedFields?: Record<string, Record<string, unknown>>;
    /** The schema describing each field present on the issue. */
    readonly schema?: Record<string, JsonTypeBean>;
    /** The URL of the issue details. */
    readonly self?: string;
    /** The transitions that can be performed on the issue. */
    readonly transitions?: Array<IssueTransition>;
    /** The versions of each field on the issue. */
    readonly versionedRepresentations?: Record<string, Record<string, Record<string, unknown>>>;
}

/** Details of an issue transition. */
export type IssueTransition = Record<string, unknown>;

/** A list of editable field details. */
export interface IssueUpdateMetadata {
    readonly fields?: Record<string, FieldMetadata>;
}

export interface JsonNode {
    array?: boolean;
    bigDecimal?: boolean;
    bigInteger?: boolean;
    bigIntegerValue?: number;
    binary?: boolean;
    binaryValue?: Array<string>;
    boolean?: boolean;
    booleanValue?: boolean;
    containerNode?: boolean;
    decimalValue?: number;
    double?: boolean;
    doubleValue?: number;
    elements?: Record<string, unknown>;
    fieldNames?: Record<string, unknown>;
    fields?: Record<string, unknown>;
    floatingPointNumber?: boolean;
    int?: boolean;
    intValue?: number;
    integralNumber?: boolean;
    long?: boolean;
    longValue?: number;
    missingNode?: boolean;
    null?: boolean;
    number?: boolean;
    numberType?: "INT" | "LONG" | "BIG_INTEGER" | "FLOAT" | "DOUBLE" | "BIG_DECIMAL";
    numberValue?: number;
    object?: boolean;
    pojo?: boolean;
    textValue?: string;
    textual?: boolean;
    valueAsBoolean?: boolean;
    valueAsDouble?: number;
    valueAsInt?: number;
    valueAsLong?: number;
    valueAsText?: string;
    valueNode?: boolean;
}

/** The schema of a field. */
export interface JsonTypeBean {
    /** If the field is a custom field, the configuration of the field. */
    readonly configuration?: Record<string, Record<string, unknown>>;
    /** If the field is a custom field, the URI of the field. */
    readonly custom?: string;
    /** If the field is a custom field, the custom ID of the field. */
    readonly customId?: number;
    /** When the data type is an array, the name of the field items within the array. */
    readonly items?: string;
    /** If the field is a system field, the name of the field. */
    readonly system?: string;
    /** The data type of the field. */
    readonly type: string;
}

/** Details a link group, which defines issue operations. */
export interface LinkGroup {
    groups?: Array<LinkGroup>;
    header?: SimpleLink;
    id?: string;
    links?: Array<SimpleLink>;
    styleClass?: string;
    weight?: number;
}

export interface Linkable {
    _links?: SelfLinkDTO;
}

export interface LinkableAttachmentLinkDTO {
    _links?: AttachmentLinkDTO;
}

export interface LinkableCustomerRequestLinkDTO {
    _links?: CustomerRequestLinkDTO;
}

export interface LinkableUserLinkDTO {
    _links?: UserLinkDTO;
}

export interface MultipartFile {
    bytes?: Array<string>;
    contentType?: string;
    empty?: boolean;
    inputStream?: Record<string, unknown>;
    name?: string;
    originalFilename?: string;
    resource?: Resource;
    size?: number;
}

/** Details of the operations that can be performed on the issue. */
export type Operations = Record<string, unknown>;

export interface OrganizationCreateDTO {
    /** Name of the organization. Must contain 1-200 characters. */
    name: string;
}

export interface OrganizationDTO {
    /** REST API URL to the organization. */
    _links?: SelfLinkDTO;
    /** Date the organization was created. This field may not be present in some older organizations. */
    created?: DateDTO;
    /** A unique system generated ID for the organization. */
    id?: string;
    /** Name of the organization. */
    name?: string;
    /** Returns if an organization is managed by scim. This field may not be present in some older organizations */
    scimManaged?: boolean;
    /** A unique system generated ID for the organization. This is identity from the group directory id */
    uuid?: string;
}

export type OrganizationServiceDeskUpdateDTO = Record<string, unknown>;

/** A page of changelogs. */
export interface PageOfChangelogs {
    /** The list of changelogs. */
    readonly histories?: Array<Changelog>;
    /** The maximum number of results that could be on the page. */
    readonly maxResults?: number;
    /** The index of the first item returned on the page. */
    readonly startAt?: number;
    /** The number of results on the page. */
    readonly total?: number;
}

export interface PagedDTOApprovalDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<ApprovalDTO>;
}

export interface PagedDTOArticleDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<ArticleDTO>;
}

export interface PagedDTOAssetsWorkspaceDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<AssetsWorkspaceDTO>;
}

export interface PagedDTOAttachmentDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<AttachmentDTO>;
}

export interface PagedDTOCommentDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<CommentDTO>;
}

export interface PagedDTOCustomerRequestDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<CustomerRequestDTO>;
}

export interface PagedDTOCustomerRequestStatusDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<CustomerRequestStatusDTO>;
}

export interface PagedDTOCustomerTransitionDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<CustomerTransitionDTO>;
}

export interface PagedDTOInsightWorkspaceDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<InsightWorkspaceDTO>;
}

export interface PagedDTOIssueBean {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<IssueBean>;
}

export interface PagedDTOOrganizationDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<OrganizationDTO>;
}

export interface PagedDTOQueueDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<QueueDTO>;
}

export interface PagedDTORequestTypeDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<RequestTypeDTO>;
}

export interface PagedDTORequestTypeGroupDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<RequestTypeGroupDTO>;
}

export interface PagedDTOServiceDeskDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<ServiceDeskDTO>;
}

export interface PagedDTOSlaInformationDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<SlaInformationDTO>;
}

export interface PagedDTOUserDTO {
    _expands?: Array<string>;
    /** List of the links relating to the page. */
    _links?: PagedLinkDTO;
    /** Indicates if this is the last page of records (true) or not (false). */
    isLastPage?: boolean;
    /** Number of items to be returned per page, up to the maximum set for these objects in the current implementation. */
    limit?: number;
    /** Number of items returned in the page. */
    size?: number;
    /** Index of the first item returned in the page. */
    start?: number;
    /** Details of the items included in the page. */
    values?: Array<UserDTO>;
}

export interface PagedLinkDTO {
    /** Base URL for the REST API calls. */
    base?: string;
    context?: string;
    /** REST API URL for the next page, if there is one. */
    next?: string;
    /** REST API URL for the previous page, if there is one. */
    prev?: string;
    /** REST API URL for the current page. */
    self?: string;
}

/** Details about a project. */
export interface ProjectDetails {
    /** The URLs of the project's avatars. */
    readonly avatarUrls?: AvatarUrlsBean;
    /** The ID of the project. */
    id?: string;
    /** The key of the project. */
    readonly key?: string;
    /** The name of the project. */
    readonly name?: string;
    /** The category the project belongs to. */
    readonly projectCategory?: UpdatedProjectCategory;
    /** The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project. */
    readonly projectTypeKey?: "software" | "service_desk" | "business";
    /** The URL of the project details. */
    readonly self?: string;
    /** Whether or not the project is simplified. */
    readonly simplified?: boolean;
}

/** Property key details. */
export interface PropertyKey {
    /** The key of the property. */
    readonly key?: string;
    /** The URL of the property. */
    readonly self?: string;
}

/** List of property keys. */
export interface PropertyKeys {
    /** Property key details. */
    readonly keys?: Array<PropertyKey>;
}

export interface QueueDTO {
    /** REST API URL to the queue. */
    _links?: SelfLinkDTO;
    /** Fields returned for each request in the queue. */
    fields?: Array<string>;
    /** ID for the queue. */
    id?: string;
    /** The count of customer requests in the queue. */
    issueCount?: number;
    /** JQL query that filters reqeusts for the queue. */
    jql?: string;
    /** Short name for the queue. */
    name?: string;
}

export interface RenderedValueDTO {
    html?: string;
}

export interface RequestCreateDTO {
    /** (Experimental) Shows extra information for the request channel. */
    channel?: string;
    /** Provides answers to the form associated with a request type that is attached to the request on creation. Jira fields should be omitted from `requestFieldValues` if they are linked to form answers. Form answers in ADF format should have `isAdfRequest` set to true. Form answers are not currently validated. */
    form?: Form;
    /** (Experimental) Whether to accept rich text fields in Atlassian Document Format (ADF). */
    isAdfRequest?: boolean;
    /** The `accountId` of the customer that the request is being raised on behalf of. */
    raiseOnBehalfOf?: string;
    /** JSON map of Jira field IDs and their values representing the content of the request. */
    requestFieldValues?: Record<string, Record<string, unknown>>;
    /** List of customers to participate in the request, as a list of `accountId` values. */
    requestParticipants?: Array<string>;
    /** ID of the request type for the request. */
    requestTypeId?: string;
    /** ID of the service desk in which to create the request. */
    serviceDeskId?: string;
}

export interface RequestNotificationSubscriptionDTO {
    /** Indicates whether the user is subscribed (true) or not (false) to the request's notifications. */
    subscribed?: boolean;
}

export interface RequestParticipantUpdateDTO {
    /** List of users, specified by account IDs, to add to or remove as participants in the request. */
    accountIds?: Array<string>;
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. Use `accountIds` instead. */
    usernames?: Array<string>;
}

export interface RequestTypeCreateDTO {
    /** Description of the request type on the service desk. */
    description?: string;
    /** Help text for the request type on the service desk. */
    helpText?: string;
    /** ID of the request type to add to the service desk. */
    issueTypeId?: string;
    /** Name of the request type on the service desk. */
    name?: string;
}

export interface RequestTypeDTO {
    /** List of items that can be expanded in the response by specifying the expand query parameter. */
    _expands?: Array<string>;
    /** REST API URL for the request type. */
    _links?: SelfLinkDTO;
    /** Whether the user has permission to create a request with this request type. */
    canCreateRequest?: boolean;
    /** Description of the request type. */
    description?: string;
    /** Fields and additional metadata for creating a request that uses the request type */
    fields?: CustomerRequestCreateMetaDTO;
    /** List of the request type groups the request type belongs to. */
    groupIds?: Array<string>;
    /** Help text for the request type. */
    helpText?: string;
    /** Links to the request type's icons. */
    icon?: RequestTypeIconDTO;
    /** ID for the request type. */
    id?: string;
    /** ID of the issue type the request type is based upon. */
    issueTypeId?: string;
    /** Short name for the request type. */
    name?: string;
    /** ID of the customer portal associated with the service desk project. */
    portalId?: string;
    /** The request type's practice */
    practice?: string;
    /** Whether request type is restricted or not. */
    restrictionStatus?: "OPEN" | "RESTRICTED";
    /** ID of the service desk the request type belongs to. */
    serviceDeskId?: string;
}

export interface RequestTypeFieldDTO {
    /** List of default values for the field. */
    defaultValues?: Array<RequestTypeFieldValueDTO>;
    /** Description of the field. */
    description?: string;
    /** ID of the field. */
    fieldId?: string;
    /** Jira specific implementation details for the field in the UI. */
    jiraSchema?: JsonTypeBean;
    /** Name of the field. */
    name?: string;
    /** List of preset values for the field. */
    presetValues?: Array<string>;
    /** Indicates if the field is required (true) or not (false). */
    required?: boolean;
    /** List of valid values for the field. */
    validValues?: Array<RequestTypeFieldValueDTO>;
    visible?: boolean;
}

export interface RequestTypeFieldValueDTO {
    /** List of child fields. */
    children?: Array<RequestTypeFieldValueDTO>;
    /** Label for the field. */
    label?: string;
    /** Value of the field. */
    value?: string;
}

export interface RequestTypeGroupDTO {
    /** ID of the request type group */
    id?: string;
    /** Name of the request type group. */
    name?: string;
}

export interface RequestTypeIconDTO {
    /** Map of the URLs for the request type icons. */
    _links?: RequestTypeIconLinkDTO;
    /** ID of the request type icon. */
    id?: string;
}

export interface RequestTypeIconLinkDTO {
    /** URLs for the request type icons. */
    iconUrls?: Record<string, string>;
}

export interface RequestTypePermissionCheckRequestDTO {
    /** The account ID of a user. */
    accountId?: string;
    /** List of requested permissions. */
    permissions?: Array<"canCreateRequest" | "canAdminister">;
    /** List of request type IDs. */
    requestTypeIds?: Array<number>;
}

export interface RequestTypePermissionCheckResponse {
    /** List of request type IDs for which the user has permission to administer. */
    canAdminister?: Array<number>;
    /** List of request type IDs for which the user can create requests. */
    canCreateRequest?: Array<number>;
}

export interface Resource {
    contentAsByteArray?: Array<string>;
    description?: string;
    file?: string;
    filename?: string;
    inputStream?: Record<string, unknown>;
    open?: boolean;
    readable?: boolean;
    uri?: string;
    url?: string;
}

/** The projects the item is associated with. Indicated for items associated with [next-gen projects](https://confluence.atlassian.com/x/loMyO). */
export type Scope = Record<string, unknown>;

export interface SelfLinkDTO {
    self?: string;
}

export interface ServiceDeskCustomerDTO {
    /** List of users, specified by account IDs, to add to or remove from a service desk. */
    accountIds?: Array<string>;
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. Use `accountIds` instead. */
    usernames?: Array<string>;
}

export interface ServiceDeskCustomerInviteDTO {
    /** Customer's name for display in the UI. */
    displayName?: string;
    /** Customer's email address. */
    email?: string;
}

export interface ServiceDeskDTO {
    /** REST API URL to the service desk. */
    _links?: SelfLinkDTO;
    /** ID of the service desk. */
    id?: string;
    /** ID of the peer project for the service desk. */
    projectId?: string;
    /** Key of the peer project of the service desk. */
    projectKey?: string;
    /** Name of the project and service desk. */
    projectName?: string;
    /** Key of the project type. */
    projectTypeKey?: string;
}

/** Details about the operations available in this version. */
export interface SimpleLink {
    href?: string;
    iconClass?: string;
    id?: string;
    label?: string;
    styleClass?: string;
    title?: string;
    weight?: number;
}

export interface SlaInformationCompletedCycleDTO {
    /** Time and date at which the SLA cycle breached in case of completed breached cycle or would have breached in case of non-breached completed cycle. */
    breachTime?: DateDTO;
    /** Indicates if the SLA (duration) was exceeded (true) or not (false). */
    breached?: boolean;
    /** Duration in which the service was completed. */
    elapsedTime?: DurationDTO;
    /** Duration within which the service should have been completed. */
    goalDuration?: DurationDTO;
    /** Duration remaining after the service was completed. */
    remainingTime?: DurationDTO;
    /** Time and date at which the SLA cycle started. */
    startTime?: DateDTO;
    /** Time and date at which the SLA cycle completed. */
    stopTime?: DateDTO;
}

export interface SlaInformationDTO {
    /** REST API URL for the SLA. */
    _links?: SelfLinkDTO;
    /** List of completed cycles for the SLA. */
    completedCycles?: Array<SlaInformationCompletedCycleDTO>;
    /** ID of the Service Level Agreement (SLA). */
    id?: string;
    /** Description of the SLA. */
    name?: string;
    /** Details of the active cycle for the SLA. */
    ongoingCycle?: SlaInformationOngoingCycleDTO;
    /** Format in which SLA is to be displayed in the UI */
    slaDisplayFormat?: string;
}

export interface SlaInformationOngoingCycleDTO {
    /** Time and date at which the SLA cycle would have breached its limit. */
    breachTime?: DateDTO;
    /** Indicates whether the SLA has been breached (true) or not (false). */
    breached?: boolean;
    /** Duration of the service. */
    elapsedTime?: DurationDTO;
    /** Duration within which the service should be completed. */
    goalDuration?: DurationDTO;
    /** Indicates whether the SLA is paused (true) or not (false). */
    paused?: boolean;
    /** Duration remaining in which to complete the service. */
    remainingTime?: DurationDTO;
    /** Time and date at which the SLA cycle started. */
    startTime?: DateDTO;
    /** Indicates whether the SLA it timed during calendared working hours only (true) or not (false). */
    withinCalendarHours?: boolean;
}

export interface SoftwareInfoDTO {
    /** REST API URL of the instance. */
    _links?: SelfLinkDTO;
    /** Reference of the change set included in the build. */
    buildChangeSet?: string;
    /** Date of the current build. */
    buildDate?: DateDTO;
    /** Indicates whether the instance is licensed (true) or not (false). */
    isLicensedForUse?: boolean;
    /** Jira Platform version upon which Service Desk is based. */
    platformVersion?: string;
    /** Jira Service Management version. */
    version?: string;
}

export type SourceDTO = Record<string, unknown>;
/** A status category. */
export type StatusCategory = Record<string, unknown>;
/** A status. */
export type StatusDetails = Record<string, unknown>;

/** A project category. */
export interface UpdatedProjectCategory {
    /** The name of the project category. */
    readonly description?: string;
    /** The ID of the project category. */
    readonly id?: string;
    /** The description of the project category. */
    readonly name?: string;
    /** The URL of the project category. */
    readonly self?: string;
}

export interface UserDTO {
    /** URLs for the customer record and related items. */
    _links?: UserLinkDTO;
    /** The accountId of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. */
    accountId?: string;
    /** Indicates if the customer is active (true) or inactive (false) */
    active?: boolean;
    /** Customer's name for display in a UI. Depending on the customer’s privacy settings, this may return an alternative value. */
    displayName?: string;
    /** Customer's email address. Depending on the customer’s privacy settings, this may be returned as null. */
    emailAddress?: string;
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    key?: string;
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    name?: string;
    /** Customer time zone. Depending on the customer’s privacy settings, this may be returned as null. */
    timeZone?: string;
}

/**
 * User details permitted by the user's Atlassian Account privacy settings. However, be aware of these exceptions:
 *
 *  *  User record deleted from Atlassian: This occurs as the result of a right to be forgotten request. In this case, `displayName` provides an indication and other parameters have default values or are blank (for example, email is blank).
 *  *  User record corrupted: This occurs as a results of events such as a server import and can only happen to deleted users. In this case, `accountId` returns *unknown* and all other parameters have fallback values.
 *  *  User record unavailable: This usually occurs due to an internal service outage. In this case, all parameters have fallback values.
 */
export interface UserDetails {
    /** The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. */
    accountId?: string;
    /** The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user) */
    readonly accountType?: string;
    /** Whether the user is active. */
    readonly active?: boolean;
    /** The avatars of the user. */
    readonly avatarUrls?: AvatarUrlsBean;
    /** The display name of the user. Depending on the user’s privacy settings, this may return an alternative value. */
    readonly displayName?: string;
    /** The email address of the user. Depending on the user’s privacy settings, this may be returned as null. */
    readonly emailAddress?: string;
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    readonly key?: string;
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    readonly name?: string;
    /** The URL of the user. */
    readonly self?: string;
    /** The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null. */
    readonly timeZone?: string;
}

export interface UserLinkDTO {
    /** Links to the various sizes of the customer's avatar. Note that this property is deprecated, and will be removed in future versions. */
    avatarUrls?: Record<string, string>;
    /** REST API URL for the customer. */
    jiraRest?: string;
    self?: string;
}

export type UsersOrganizationUpdateDTO = Record<string, unknown>;

export interface RateLimitError {
    message?: string;
    retryAfter?: number;
}
